### ISSUE TITLE
Pump treatments are 12 hours in the future

### ISSUE THREAD

**Issue by old-square-eyes** [openaps/oref0#1263] opened 2019-05-27 11:57 UTC
I'm new but after days of digging and asking online and reading the docs I'm stumped.

Most Open APS treatments are shown as in the future in NS admin tools. But all timestamps match across all my devices and the UI in NS is current to what is happening i.e. tmp basals are current in the UI. How is NS deciding there is an issue? https://www.facebook.com/groups/TheLoopedGroup/permalink/2272196186330368/

My local time is Pacific/Auckland and is set on NS and OAPS, and manually on my pump (though that gets synced)

Inspecting the logs I see...

`Checking deliverAt: 2019-05-27T11:44:29.995Z is within 1m of current time: Mon May 27 23:44:30 NZST 2019`

When you drop the first timestamp in a converter it's 12 hours out to what my local time is (11:44pm)

https://www.silisoftware.com/tools/date.php?inputdate=2019-05-27T11%3A44%3A29.995Z&inputformat=text

I have triple checked all my device clocks are correct and have rerun setup and instructions here...

https://openaps.readthedocs.io/en/latest/docs/Troubleshooting/oref0-setup-troubleshooting.html#re-run-the-script-again

and here..

https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/usability-considerations.html?#what-do-you-do-with-your-loop-when-you-travel-across-timezones-how-do-you-update-devices-for-a-time-zone-change

(Including deleting the contents of the OpenAPS monitor folder)

To make matters worse, these future treatments appear in xDrip when 12hours rolls round.

**Comment by sulkaharo** [comment] 2019-05-27 14:17
@old-square-eyes Can you post some sample data from your Nightscout in JSON format or given me your NS URL so I can check things? By having set the time zone, you mean this is set in the Nightscout profile and for the OpenAPS rig Linux environment?

**Comment by old-square-eyes** [comment] 2019-05-27 19:42
In OpenAPS -
Time zone Pacific/Auckland
~# date
Tue May 28 07:28:11 NZST 2019
Which is correct. 

'Checking deliverAt: 2019-05-27T19:34:23.008Z is within 1m of current time: Tue May 28 07:34:23 NZST 2019' 
From log tail

**Comment by old-square-eyes** [comment] 2019-05-27 19:50
I have it set in both NS profile and OAPS Linux and NS profile is Pacific /Auckland.

Will pm NS on gitter.

**Comment by old-square-eyes** [comment] 2019-05-27 22:52
https://files.gitter.im/nightscout/intend-to-bolus/bjRs/image.png

This doesn't seem right myOpenAPS/monitor/clock-zoned.json

Or is it?

**Comment by scottleibrand** [comment] 2019-05-27 23:57
Umm... is that what time it was, or not? What makes you think it’s not right?

**Comment by old-square-eyes** [comment] 2019-05-28 01:41
Clutching at straws. Time zones confuse me. To verify.
At 13:41 right now in Auckland the contents of this file is "2019-05-28T13:39:30+12:00"

**Comment by scottleibrand** [comment] 2019-05-28 02:02
That means it was 13:39 in the time zone 12h ahead of UTC, which is correct.

**Comment by sulkaharo** [comment] 2019-05-28 05:38
Hey to confirm - what’s the time zone setting on the computer you’re using to access Nightscout?

**Comment by sulkaharo** [comment] 2019-05-28 05:42
As Scott says, NZST is 12 hours ahead of UTC, so the time comparison sample above is correct (even if the log message is confusing given the time logged are in different zones).

**Comment by old-square-eyes** [comment] 2019-05-28 06:44
OK great. At least we're ruling things out. Much appreciated. TZ of NS computer is set to auto (Mac Mojave).

Currently...

<img width="320" alt="image" src="https://user-images.githubusercontent.com/25760491/58456573-a83adf80-8178-11e9-8779-6f7aa2c94c98.png">

**Comment by sulkaharo** [comment] 2019-05-28 06:54
Looks like this is a regression in the Nightscout admin tool (or, some layer below). The admin tool implementation for the feature is not very robust, but also looks like the query it's making is interpreted wrong by some layer of the database. Checking.

**Comment by sulkaharo** [comment] 2019-05-28 13:16
This should fix this issue: https://github.com/nightscout/cgm-remote-monitor/pull/4658

**Comment by old-square-eyes** [comment] 2019-05-29 07:57
Thanks for looking at this. I'm only really just starting to increase my NS usage since closing the loop (previously just a convenient monitor). How long would a change like this take to make it to master branch?

**Comment by sulkaharo** [comment] 2019-05-29 08:28
This making it to master depends on how much testing help I get :D You switch branches by using the upgrade tool and pulling from dev instead of master. The current dev should be stable, so you’re getting a master early if you halo test this now.

**Comment by old-square-eyes** [comment] 2019-05-29 08:48
Fair point. I'll give it a try. Will it permanently alter data going in to Nightscout? Are there any risks I should be aware of?

**Comment by sulkaharo** [comment] 2019-05-29 08:50
It’ll change how treatment timestamps are saved. Existing data is not changed. If you see any adverse effects during the first 12 hours after the update (your time difference to UTC), I’d love to hear about that.

**Comment by old-square-eyes** [comment] 2019-05-29 08:52
OK will do :)

**Comment by old-square-eyes** [comment] 2019-05-29 09:09
Curious. Do the OAPS devs know? Presumably it's better in the long term for the most appropriate format to be used.

**Comment by danamlewis** [comment] 2019-10-21 00:29
It sounds like this was resolved in NS; please open a new issue if needed if this is still an issue with the latest NS release and 0.7.0-dev on the OpenAPS side.

**Closed by danamlewis** 2019-10-21 00:29 UTC

**Comment by old-square-eyes** [comment] 2019-11-13 02:51
May need to reopen this one per @sulkaharo 

https://omniaps.slack.com/archives/CNW9XR741/p1571635660170700

Interestingly I got some strange TZ issues after upgrading from Dev to 0.7.0 Master. Loops are failing saying BG is old. Reported delta is ~60 minutes and we are in DST currently.
