### ISSUE TITLE
recurring 'Could not get subg_rfspy state or version' errors

### ISSUE THREAD

**Issue by rainbow-lazer** [openaps/oref0#996] opened 2018-05-07 19:45 UTC
I've been experiencing this on one of my boards over the last month or so running 0.6.1. Tried all the troubleshooting tips in the docs, as well as re-flashing a couple times. The fix lasts a few days at most, then back to a flaky radio One thing I notice is that if the rig loses connection with the pump, it seems to throw it into the 'subg_rfspy state or version' error...

Per Facebook conversation with Katie DiSimone and Dana M. Lewis, I'm also attaching screenshots of oref0-runagain after installing 0.7.0-dev and answering the cron questions: [1](https://www.dropbox.com/s/u7zfgwf6uq28ljs/Screen%20Shot%202018-05-07%20at%202.50.03%20PM.png?dl=0) [2](https://www.dropbox.com/s/t53tqlqaucn5ndf/Screen%20Shot%202018-05-07%20at%202.50.26%20PM.png?dl=0)

**Comment by tim2000s** [comment] 2018-05-07 20:03
The issue is that you’ve two pump-loops competing in the cron job. When you run install you need to allow it to delete your old cron @rainbow-lazer

**Comment by rainbow-lazer** [comment] 2018-05-07 20:05
Thanks Tim! I thought that I'd done that (I think you're referring to the 'Would you like to remove your existing crontabs first?' prompt; is that correct?)

**Comment by Ashley112885** [comment] 2018-05-13 15:38
I’m having the same issue with new hw. I had it happen with two brand new rigs, one of which I was able to get looping again. The other one started looping for a few hours but then stopped again.

**Comment by Kdisimone** [comment] 2018-05-13 15:49
I’ve seen this happen on Jacob’s two brand new rigs; he hadn’t gotten them to Loop at all. He mailed them to me and it took many many flashes of both ccprog and jubilinux to get the boards working again. Was not a duplicate cron issue for his boards. 

Also Steve Mann reported similar in gitter oref0 channel. Martin was helping him through reflashing and troubleshooting, and said he had experienced same issue. 

I went through this one time too. 

Part of the problem is that the error seems to spread. If one rig gets affected and you switch it to another explorer board to troubleshoot, the new combinations will be affected too. Multiple people have reported same.

**Comment by rainbow-lazer** [comment] 2018-05-13 20:36
Yes, seems like the error I’m encountering got slightly better after fixing
the multiple caron issue, but still recurs. I can now seem to fix it with
multiple (5-6) reboots though.

**Comment by antonio** [comment] 2018-05-14 09:18
This has been happening to me in my two rigs as well, and it turned out to be caused by the nuts and bolts that I was using.

Since it works for you after re-flashing the radio firm, it's unlikely that this info can help you but I'm dropping it here anyway in case it can help to future readers of this issue that are trying to figure out the reason why their radio does not work :smile:

**Comment by tim2000s** [comment] 2018-05-14 21:42
Okay. We’ve come up with a load of theories on this one. Is it possible it’s simply about how the Edison/Explorer board interface is seated? That’s what a nuts and bolts discussion would suggest?

**Comment by rainbow-lazer** [comment] 2018-05-14 22:10
I'm a bit skeptical that mounting screws the cause, but of course it is
possible. Obviously the board needs to be seated securely, but beyond that
how much variation could there be in a set of machine screws?

There was also some discussion on the initial Facebook thread that it could
be due to using the bootstrap script vs doing the post-flash setup the
manual/step-by-step way. That seems more plausible to me as I've been able
to [temporarily] fix the issue with a re-flash or other software steps as
outlined in the troubleshooting docs.

On the third hand, maybe it's a combination of these things?

**Comment by scottleibrand** [comment] 2018-05-14 22:28
I can imagine how bent pins would "spread", by bending the corresponding pins on the other side of the connector.  I can't imagine how the issue could spread from Edison to Explorer and back if it were a  software issue, as the only software on the Explorer Board is the subg_rfspy firmware, and there's no mechanism by which that could execute any code on the Edison.

**Comment by Kdisimone** [comment] 2018-05-14 23:14
But the pins have been sitting in working rigs. Without damage. Without impact. And then stop working.

**Comment by Kdisimone** [comment] 2018-05-14 23:14
And it’s only radio error. Everything else goes great. And fixed with multiple reflashes. Doubt it’s pins

**Comment by Ashley112885** [comment] 2018-05-14 23:18
Yeah I got a rig from Katie that was working fine for first couple days then stopped giving the infamous error. Which is when I started swapping boards with my spare rig and the error transferred like Katie stated above.

**Comment by Kdisimone** [comment] 2018-05-14 23:36
This is a pretty good long thread where you can read...Martin apparently had similar.  found a "solution" but then Steve basically got his to work eventually...but had the error spread too before it fixed.

**Comment by Kdisimone** [comment] 2018-05-14 23:39
https://gitter.im/openaps/oref0?at=5ad4d533102fac7b7b1ab5b3

**Comment by antonio** [comment] 2018-05-15 08:58
> @antonio, what nut/bolt/spacer set did you end up using that worked for you?

So what I've found to be working for me is to only use them in the socket next to the USB ports. The ones I'm using exactly come from [this set](https://www.amazon.es/gp/product/B01M7P8C07).

**Comment by rainbow-lazer** [comment] 2018-05-24 14:16
If it is a spacing/attachment issue, would it make sense that there would
also be some visible deformation in the pins?

On my end, I'm still getting this error pretty regularly. I just ran the
mmtune command (`killall -g oref0-pump-loop; openaps mmtune') from the
troubleshooting page and get this:

`
Traceback (most recent call last):

  File "/usr/local/bin/openaps-report", line 82, in <module>

    app( )

  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py",
line 51, in __call__

    self.run(self.args)

  File "/usr/local/bin/openaps-report", line 75, in run

    output = app(args, self)

  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py",
line 52, in __call__

    return self.method.main(args, app)

  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py",
line 40, in main

    output = task.method(args, app)

  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line
45, in __call__

    output = self.main(args, app)

  File
"/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/mmeowlink.py",
line 100, in main

    return self.mmtune.run( )

  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/mmtune.py", line
53, in run

    results = self.scan_over_freq(self.scan_range['start'],
self.scan_range['end'], 25)

  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/mmtune.py", line
96, in scan_over_freq

    results.append(self.run_trial("%0.3f" % cur_freq))

  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/mmtune.py", line
77, in run_trial

    packet = self.get_packet(0.080)

  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/mmtune.py", line
107, in get_packet

    return self.link.get_packet(timeout)

  File
"/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py",
line 185, in get_packet

    return self.handle_response(resp)

  File
"/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py",
line 152, in handle_response

    raise CommsException("Received an error response %s" %
self.RFSPY_ERRORS[ resp[0] ])

KeyError: 1

Usage: grep [OPTION]... PATTERN [FILE]...

Try 'grep --help' for more information.

root@edisonhost-mobile:~/myopenaps#

Broadcast message from root@edisonhost-mobile (Thu 2018-05-24 10:13:02 EDT):


Rebooting to fix radio errors!

The system is going down for reboot at Thu 2018-05-24 10:18:02 EDT!
`

**Comment by Ashley112885** [comment] 2018-05-30 14:23
I just confirmed that removing the screws has resolved this issue 😳

**Comment by jpcunningh** [comment] 2018-05-31 00:21
YMMV:

https://www.sparkfun.com/products/13041

**Comment by Kdisimone** [comment] 2018-05-31 01:36
Well this is mighty encouraging!  Woohooo

**Comment by rainbow-lazer** [comment] 2018-06-02 03:49
I’ve also tried removing the screws and still get the same error.

**Comment by rainbow-lazer** [comment] 2018-06-13 14:36
Still getting this error regularly. As a stop-gap, I've added this line to
my crontab which seems to help: `@reboot (cd myopenaps; killall -g
oref0-pump-loop; openaps mmtune)`.

**Comment by danamlewis** [comment] 2019-10-20 23:59
Have not heard of this being an issue with 0.7.0-related rigs; closing. Please re-open if someone is on 0.7.0-dev and still having recurring issues.

**Closed by danamlewis** 2019-10-20 23:59 UTC
