### ISSUE TITLE
get_pref_string not working, causes loop failure with MEDTRONIC_PUMP_ID environment variable not set

### ISSUE THREAD

**Issue by dcacklam** [openaps/oref0#1233] opened 2019-03-20 07:16 UTC
**Describe the bug**
get_pref_string is returning 'nothing', causing variables to be unset & the loop to not work at all

**To Reproduce**
1. Have a working Oref0 dev rig
2. Git pull to current branch status
3. Copy your old preferences.json over the newly generated one.
4. Everything breaks, as environment variables are left unset.
5. Hardcoding some of the values (like MEDTRONIC_PUMP_ID) makes the related broken functionality start to come back, but the function is too widely used for this to be even a temporary fix

**Smartphone (please complete the following information):**
Pixel 3XL

**Setup Information (please complete the following information):**
Medtronic 722
Edison with Explorer
Oref0 0.7.0-dev

**Comment by cluckj** [comment] 2019-03-20 17:00
The issue is definitely caused by migrating away from using `pump.ini` to `preferences.json`. `oref0-setup.sh` automatically merges/adds the `pump_serial` and `radio_locale` preferences, but if you didn't run it (or copied an old preferences file over) then it won't be there. 

Can you manually add the following to the end of your preferences.json and see if that resolves the issue?
```
  "pump_serial": "put your pump serial number here",
  "radio_locale": "US"
```

**Comment by bewest** [comment] 2019-03-20 17:37
BTW, `openaps device show pump --json` will convert `pump.ini` to json for you automatically.

**Comment by bewest** [comment] 2019-03-20 17:38
`openaps` has json export and import features. 😸

**Comment by oleg-post** [comment] 2019-04-12 15:22
doesn't help. Still the same error.

**Comment by N3FM** [comment] 2019-09-18 02:17
Same issue on newly installed 0.7.0-dev with 530 pump and Edison explorer.  Manually running mmtune also reports MEDTRONIC_PUMP_ID not initialized.  Do we have a workaround in the interim? I'm ok with hardcoding on a temporary basis

**Comment by scottleibrand** [comment] 2019-09-18 02:27
For interactive runs, you can just `export MEDTRONIC_PUMP_ID=yourserialnumber` on the command line before running the command.

**Comment by danamlewis** [comment] 2019-10-21 00:25
Closing as error is related to copying preferences over the new preferences file when upgrading. Added to 0.7.0 release testing notes to address.

**Closed by danamlewis** 2019-10-21 00:25 UTC
