### ISSUE TITLE
COB can be incorrectly reported as zero

### ISSUE THREAD

**Issue by thebookins** [openaps/oref0#760] opened 2017-10-27 10:10 UTC
I have noticed a few times COB being incorrectly reported as zero soon after a meal. oref0 can act on this information and enact a zero temp. The problem usually self-resolves but if the rig stops working after this false COB is acted upon (e.g. kid walking away from rig) a higher-than-expected BG could result.

In discussion on gitter with @scottleibrand it was surmised that this could occur with a poor internet connection. If carb information isn't downloaded properly from NS, this could also be affecting carbs read from the pump.

Below is the `pump-loop.log` showing one of these occasions. All carb information was entered through the pump. On the first iteration `mealCOB` is 105, on the second it is 0, and on the third it is 101.

```text
Autotune exists! Hoorah! You can use microbolus-related features.
{"carbs":140,"mealCOB":105,"currentDeviation":23.79,"maxDeviation":38.68,"minDeviation":11.43,"slopeFromMaxDeviation":-2.992,"slopeFromMinDeviation":1.376,"allDeviations":[24,28,29,39,37,29,11],"lastCarbTime":1508831690000}
BG data is too old (it's probably this), or clock set incorrectly.  The last BG data was read at Tue Oct 24 2017 19:21:55 GMT+1100 (AEDT) but your system time currently is Tue Oct 24 2017 19:32:21 GMT+1100 (AEDT)
  "reason": "BG data is too old (it's probably this), or clock set incorrectly.  The last BG data was read at Tue Oct 24 2017 19:21:55 GMT+1100 (AEDT) but your system time currently is Tue Oct 24 2017 19:32:21 GMT+1100 (AEDT)"
Checking system clock against pump clock:
Checking deliverAt: null is within 1m of current time: Tue Oct 24 19:32:21 AEDT 2017
date: invalid date ‘null’
supermicrobolus pump-loop failed. Listening for 40s silence before mmtuning: .No interfering pump comms detected from other rigs (this is a good thing!)
mmtune: "916.660", 5, -84 waiting for 48 second silence before continuing
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Done waiting for rigs with better signal.
Unsuccessful supermicrobolus pump-loop at Tue Oct 24 19:34:18 AEDT 2017
Starting supermicrobolus pump-loop at Tue Oct 24 19:35:02 AEDT 2017 with 6 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK. Profile less than 60m old. Refreshed pumphistory! and meal.json
Checking pump clock: "2017-10-24T19:35:52+11:00" is within 1m of current time: Tue Oct 24 19:35:53 AEDT 2017
and that pumphistory is less than 1m old.  Temp refreshed
Autotune exists! Hoorah! You can use microbolus-related features.
{"carbs":0,"mealCOB":0,"currentDeviation":15.47,"maxDeviation":38.68,"minDeviation":20.27,"slopeFromMaxDeviation":-4.051,"slopeFromMinDeviation":0,"allDeviations":[15,20,24,28,29,39,37,29],"lastCarbTime":0}
{"iob":5.636,"activity":0.0416,"basaliob":-0.817,"bolusiob":6.453,"netbasalinsulin":-1.55,"bolusinsulin":10.8,"time":"2017-10-24T08:35:57.000Z","iobWithZeroTemp":{"iob":5.636,"activity":0.0416,"basaliob":-0.817,"bolusiob":6.453,"netbasalinsulin":-1.55,"bolusinsulin":10.8,"time":"2017-10-24T08:35:57.000Z"},"lastBolusTime":1508831690000,"lastTemp":{"rate":0,"timestamp":"2017-10-24T19:25:26+11:00","started_at":"2017-10-24T08:25:26.000Z","date":1508833526000,"duration":11.58}}
{"delta":-12,"glucose":113,"short_avgdelta":-8.67,"long_avgdelta":1.12}
Autosens ratio: 1; Basal unchanged: 1.1; ISF unchanged: 108
currenttemp: { duration: 21, rate: 0, temp: 'absolute' } lastTempAge: 11 m tempModulus: 2 m
Carb Impact: 10.5 mg/dL per 5m; CI Duration: NaN hours; remaining CI (~2h peak): NaN mg/dL per 5m
UAM Impact: 10.5 mg/dL per 5m; UAM Duration: 0.3 hours
minPredBG: -324 minIOBPredBG: 39 minZTGuardBG: -324 avgPredBG: -324 COB: 0 / 0
BG projected to remain above 117 for 0 minutes
BG projected to remain above 78.5 for 15 minutes
naive_eventualBG: -496 bgUndershoot: 574.5 zeroTempDuration: 15 zeroTempEffect: 30 carbsReq: 86
Checking deliverAt: 2017-10-24T08:36:08.491Z is within 1m of current time: Tue Oct 24 19:36:08 AEDT 2017
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"insulinReq":0,"bg":113,"reservoir":"155.3","temp":"absolute","carbsReq":86,"predBGs":{"ZT":[113,91,68,45,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"IOB":[113,100,86,71,56,39,39,39,39,39,39,39,39]},"IOB":5.636,"reason":"COB: 0, Dev: 63, BGI: -22.46, ISF: 6.0, Target: 6.5, minPredBG -18.0, minGuardBG -24.3, IOBpredBG 2.2; 86 add'l carbs req w/in 15m; minGuardBG -24.3<4.4 21m left and 0 ~ req 0U/hr: no temp required","COB":0,"eventualBG":-433,"tick":-12,"deliverAt":"2017-10-24T08:36:08.491Z"}
No smb_enact needed. Temp refreshed: monitor/temp_basal.json: {"duration":20,"rate":0,"temp":"absolute"}
No bolus needed (yet). Settings less than 15 minutes old. Edison on battery: 39%. pumphistory-24h refreshed
Completed supermicrobolus pump-loop at Tue Oct 24 19:36:26 AEDT 2017
Starting supermicrobolus pump-loop at Tue Oct 24 19:37:03 AEDT 2017 with 13 second wait_for_silence:
Waiting up to 4 minutes for new BG: ...................glucose.json newer than pump_loop_completed
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK. Profile less than 60m old. Refreshed pumphistory!!!!! and meal.json
\Checking pump clock: "2017-10-24T19:41:20+11:00" is within 1m of current time: Tue Oct 24 19:41:21 AEDT 2017
and that pumphistory is less than 1m old.  Temp refreshed
Autotune exists! Hoorah! You can use microbolus-related features.
{"carbs":140,"mealCOB":101,"currentDeviation":9.52,"maxDeviation":38.68,"minDeviation":15.47,"slopeFromMaxDeviation":-4.28,"slopeFromMinDeviation":0,"allDeviations":[10,15,20,24,28,29,39,37,29],"lastCarbTime":1508831690000}
```

**Comment by PieterGit** [comment] 2017-10-27 12:02
@thebookins : I can confirm this with my oref0 0.6.0 dev  `Sun Oct 8 19:49:39 2017 -0700` (yeah, I need to update). I have also seen this happening. Did you manage to find an idea of what files / aliases we need to check to solve this problem?

**Comment by thebookins** [comment] 2017-10-27 21:13
@PieterGit No, I'm not sure what's causing this. Thinking of having a look at `oref0-ns-loop.sh` first, to see if it's caused by an error downloading carbs from NS. There doesn't look to be anything suspicious in `pump-loop.log`.

**Comment by bdr1177** [comment] 2017-10-31 15:03
I have also had problems with this same issue since going to 0.6.0 dev.  In one case, OpenAPS acknowledged the additional IOB from a bolus wizard entry, but did not initially acknowledge the COB (see below).  The rig set a zero temp based on the IOB and no COB.  I agree that this is a potential problem, especially for kids who often wander out of range at home or at school.
![capture9](https://user-images.githubusercontent.com/8519000/32231070-04ad0efe-be2b-11e7-9702-0e754a16ccd1.JPG)

**Comment by scottleibrand** [comment] 2017-11-05 00:47
I've updated oref0-ns-loop to check the downloaded carbhistory.json.new is valid json before copying it over to carbhistory.json, which may help somewhat.

If it's not that, someone will probably need to work on figuring out how to reproduce this before we'll be able to start working on fixing it.

**Comment by scottleibrand** [comment] 2017-11-14 02:00
Closing this for now as potentially resolved.  If you see anything similar on 0.6.0-dev5 or newer, please open a new issue.

**Closed by scottleibrand** 2017-11-14 02:00 UTC
