### ISSUE TITLE
high temp if (bad) BG data jumps high just for one reading even if BG is falling 

### ISSUE THREAD

**Issue by libxmike** [openaps/oref0#467] opened 2017-05-11 15:32 UTC
ppl who are not using Dex for BG monitoring but Libre with Limitter get some times one high readings >200mg/dl just for one data set what causes high temp  even if BG is going down like few times in my case. 2nd problem is with flat line if Libre sensor expires after 14.5 days, last value will be read and send  continuously to NS if transmitter still attached and sending data

**Comment by PieterGit** [comment] 2017-05-12 07:08
@libxmike This is a serious issue, but I don't think it's a oref0 issue. Because of the Seperation Of Concern principles (https://en.wikipedia.org/wiki/Separation_of_concerns ) these issue should imho not be fixed in oref0, but in the Libre application uploading the BG data (Limitter) in your case.

I think CGM devices should:
- do some filtering of the (bad) BG glucose data if the technology requires that (prevent spikes that are inaccurate). If you compare raw data from a G4 you'll see that the Dexcom also does some kind of filtering. I think Limitter should also implement this 

- don't provide BG data if it's not accurate (for example sensor expired). I know the Libre sensor can detect that. It should not sent bad BG data to openaps in that case. By design if no fresh BG data has been entered OpenAps/Oref0 will not sett temps.

**Comment by PieterGit** [comment] 2017-05-12 07:16
I noticed there is a mechanism in place for xdrip to sent an expiry message after 5 BG's that are the same
https://github.com/JoernL/LimiTTer/issues/10  
I think 5*5 = 25 minutes is too long, but that's an implementation responsibility of the CGM-device.

**Comment by libxmike** [comment] 2017-05-12 07:18
the code from Joern is not in use anymore, we use one from @keencave which is more advanced

**Comment by libxmike** [comment] 2017-05-12 07:19
I talked about the issue with Scott yesterday and as there are too many transmitters and software for Libre sensors oref0 solution would be the best way

**Comment by PieterGit** [comment] 2017-05-12 07:46
I disagree with @scottleibrand on this one. It would not be the best way, but the easiest way. Fixing somebody elses problems in another layer or application is plain wrong (sorry I met Edsger Dijkstra once).  OpenAPS/oref0 should be able to trust the cgm device (Nightscout in think in this case) to provide valid CGM-data.  

What can be done is implement a (configurable) limit to oref0 of the maximum bg glucose (lets say default 280).  That would also benefit openaps/oref0 safety. Libre users can set that lower, but that's a workaround for the root cause (bad CGM data).

**Comment by scottleibrand** [comment] 2017-07-02 03:09
@AdrianLxM do you know what the current situation is with Libre?  Is the sensor-expired issue something we'll need to work around in OpenAPS, or will they be fixing it properly in xDrip+?

**Comment by AdrianLxM** [comment] 2017-07-02 04:53
As far as I understood @jamorham, it was never an issue in xDrip+.
It was only people having set their input method to xBridge and not LimiTTer.
xDrip even detects whether it is a LimiTTer or an xBridge by the BT name.

So far I have only seen this in the German group where they passed an unofficial pre-release firmware for the LimiTTer that falsely reported to be an xBridge.

**Comment by AdrianLxM** [comment] 2017-07-02 05:05
@libxmike, if you use the keencave firmware please update it. The latest version should now report itself as "LimiTTer".

@jamorham, I remember we had a general deduping of exactly the same raw values in for Dexcom as well. It seems to have gone - or did it not make it the xDrip+ fork? This would have prevented this as it would have not sent any more (false) data that was used for looping and would have risen a missed readings alert after a short while.

**Comment by scottleibrand** [comment] 2017-07-17 00:35
Anything else we need to do for this in oref0?  Or should we close this?

**Comment by scottleibrand** [comment] 2017-10-09 02:32
We've since added a check to determine-basal which should help with this: https://github.com/openaps/oref0/blob/dev/lib/determine-basal/determine-basal.js#L683-L687

And see also https://github.com/openaps/oref0/pull/690 and https://github.com/NightscoutFoundation/xDrip/issues/191

**Closed by scottleibrand** 2017-10-09 02:32 UTC
