### ISSUE TITLE
mm-format-ns-treatments does not work with Nightscout in mmol/L mode

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#62] opened 2016-01-30 22:07 UTC
I currently see openaps upload it in mg/dL format. 
But my nightscout is in mmol/L mode and interprets the bloodvalues wrong.

Example upload:
"amount": 140,
"eventType": "<none>",
"glucose": 140,
"glucoseType": "Finger",
"notes": "Pump received finger stick.",
"medtronic": "mm://openaps/mm-format-ns-treatments/CalBGForPH",
"created_at": "2016-01-30T21:36:06+01:00",
"enteredBy": "openaps://medtronic/754"

According to @bewest on gitter:
that's a bug and should be logged/tracked
yup that's a gap in the current tools
issue here is reverse though
the pump-history, the bg stuff seems to always be in mg/dL

I din't get adding ?units=mg/dL to your NS endpoint working
it could be argued that a patch to mm-format-ns-treatments should handle this maybe

**Comment by PieterGit** [comment] 2016-01-30 22:38
fix/work around. change oref0/bin/ns-upload.sh to
REST_ENDPOINT="${NIGHTSCOUT_HOST}/api/v1/${TYPE}\?units=mg/dL"
I can confirm that that works.

**Comment by scottleibrand** [comment] 2016-01-30 22:59
No downside to that, is there? Want to submit it as a PR?

-Scott




On Sat, Jan 30, 2016 at 2:38 PM -0800, "PieterGit" <notifications@github.com> wrote:












fix/work around. change oref0/bin/ns-upload.sh to

REST_ENDPOINT="${NIGHTSCOUT_HOST}/api/v1/${TYPE}\?units=mg/dL"

I can confirm that that works.

**Comment by PieterGit** [comment] 2016-01-30 23:00
will have a look at it tomorrow.  will try to create a PR. not a git/github guru yet.

**Comment by bewest** [comment] 2016-01-30 23:44
You'd be better off adding it to the `TYPE` when you add a device:

```
openaps device add ns-upload-treatments process ns-upload $host $secret "treatments.json?units=mg/dL" ...
```

`ns-upload` is a pretty generic tool; I used to also look for `NIGHTSCOUT_PARAMS` for extra parameters like this, but figured it's more easily put in the `TYPE` argument.  Let know what you think.

**Comment by bewest** [comment] 2016-01-30 23:46
Specifically, for more context, `ns-get` and `ns-upload` are complementary, they do the inverse thing for any data type, so shouldn't force arguments on all possible uses.

It would make a lot of sense to create a separate tool called `ns-upload-oref0-treatments` (more purpose built) that handles these settings automatically.

**Comment by PieterGit** [comment] 2016-01-31 18:56
Does oref0 universally uses mg/dL for data? This would helps ensure user safety by ensuring we never mix up mg/dL and mmol/L.

I noted that @oskarpearson in this commit for openaps:
https://github.com/openaps/openaps/commit/ca024cf010fc18728f0eb81652082eca10da9dc7
uses two fields:
- 'user-preferred-units': This reflects what the pump-owner prefers their unit of measurement to be.
- 'units': the units, always set explicit to 'mg/dL'

I had a look at PEP 20 -- The Zen of Python, https://www.python.org/dev/peps/pep-0020/
The following design rules are related to this issue:
1. Explicit is better than implicit. ==> explicitly add a field units and/or user-prefered-units
2. In the face of ambiguity, refuse the temptation to guess. ==> oref0 should not guess that it is in mg/dL, but the stuff at the edges (pump readings, upload to ns) should make sure the right unit is used.

I think that adding it to the TYPE (e.g. "treatments.json?units=mg/dL") or NIGHTSCOUT_PARAMS is not the way to go (too error prone).

Am I right that the following route should be implemented?
- adding the fields "units" and "user-preferred-units" to oref0/lib/temps.js and oref0/lib/bolus.js and possible other places
- be explicit about the preffered units in ns-get and ns-upload

**Comment by scottleibrand** [comment] 2016-05-15 01:43
Has this been resolved with any of @bewest's newer tools?

**Comment by bewest** [comment] 2016-05-15 01:48
`get-profile` expects units.  I think the feedback might be condensed as: "units tool should support treatments type."

**Comment by scottleibrand** [comment] 2016-05-15 02:32
Not sure I follow. Perhaps someone using mmol will need to do at least the first pass at this?

**Comment by cjo20** [comment] 2016-07-12 00:21
If it's just for finger prick readings, my current hack is to change `oref0/lib/pump.js`, changing 
`current.glucose = current.amount;`
to something like
`current.glucose = Math.round(10 * (current.amount / 18)) / 10;`

Obviously that isn't a long-term solution, but it seems to work ok for now.

**Comment by jasoncalabrese** [comment] 2016-07-12 00:34
I think we can also include the units and NS should be able to use it

**Comment by PieterGit** [comment] 2016-10-09 15:25
i currently use the oref0-setup.sh script. I don't the this uses mm-format-ns-treatments (or am I wrong). What's the way forward with this issue?

**Comment by scottleibrand** [comment] 2016-12-04 02:38
I think we're stalled here.  If this is still an issue we want to fix, can someone reproduce the problem with the latest code and detail exactly what is being done incorrectly in oref0?

**Comment by sulkaharo** [comment] 2017-01-03 15:03
FWIW with our pump, the problem is the pump using mixed units based on how the data was produced. I tried looking into a good fix, but this would require decocare would flag the decoded packet with the units, as known to produce by the specific pump model.

**Comment by scottleibrand** [comment] 2017-02-07 04:12
@sulkaharo @PieterGit so is this something we can work on, or should I close this issue?

**Comment by cjo20** [comment] 2017-02-07 13:45
It's something that should be worked on. Over time I'm trying different fixes to try and work out what will actually give correct values. I *think* there might be an issue in the way nightscout converts the BGs for display (I can get the data point to appear in the right place, but the BG text is 18x too small), and I'm trying to work out if it needs to be fixed in openaps or nightscout.

**Closed** 2017-10-09 02:44 UTC
