### ISSUE TITLE
Issue with Dev on Explorer board, radio related. 

### ISSUE THREAD

**Issue by Bender1061** [openaps/oref0#522] opened 2017-07-04 20:20 UTC
So there is something seriously an issue with the Dev release. it's extremly unreliable now. I've done this on 3 Explorer board rigs now. One of them works somewhat reliable, but the others I'm lucky if it completes a loop an hour. Reduced running of mmtune, so that may be part of the issue, but It's in the Where it should be running the Precheck. I get several different errors mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low? so with that, I decided to do the ccprog. Once I do that, stderr: 'fatal: Not a git repository (or any of the parent directories): .git' happens about 80% of the time. Now on my Non Explorer board rigs, it works fine. So I'm thinking it has something to do with the explorer board. And this was not happening on the #514 so it's something that was added before we added this to Dev.

**Comment by ceben80** [comment] 2017-07-04 20:26
I have been running the current dev, no issues so far, but using one of the first Explorer Board (w/ 500mA charging current)

**Comment by PieterGit** [comment] 2017-07-04 20:29
I noticed this as well with a 754 WW pump and second generation  Explorer board.
I don't know the exact trigger, but I know a workaround (which works for me):
- stopping the loops `/etc/init.d/cron stop` 
- waiting for the pump loop to end
- using a `openaps mmtune` 
- starting the loops `/etc/init.d/cron start`

I have bad experience with using `killall` on the pump loop or killing pump processes. It can seriously disturb pump communication. Not only on the rig, but I had several issues taht required the pump to be reset by by removing and reinserting the battery. After that and a manual `openaps mmtune` the problem disappears.

**Comment by Bender1061** [comment] 2017-07-04 20:31
That is pretty much what I did with the one that is reliable. other than I just comment out the cron lines and do a reboot. Cause you are correct the killall is sort of strange at times.

**Comment by scottleibrand** [comment] 2017-07-04 20:56
#523 might help with this somewhat.  it changes mmtune back to running on 25% of failures (instead of just 15%) and removes the unless() loop to help minimize the need to killall (as @PieterGit originally suggested).

**Comment by PieterGit** [comment] 2017-07-04 21:10
I meant +1'ing the PR https://github.com/openaps/oref0/pull/523. It saves some of the killing of the pump loop.  I will update a test rig later this week or this weekend. I don't have any git (corruption) errors BTW.

I've been thinking of some kind of https://en.wikipedia.org/wiki/Exponential_backoff mechanism to find the optimum of running mmtune and not draining the rig battery or overheating the edison/radio with continuous pump communication. For example:

1st time in case of mmeowlink.exceptions.CommsException (or other error) immediately call mmtune
2nd time in case of mmeowlink.exceptions.CommsException (or other error)  mmtune 75% of the time
3rd time  in case of mmeowlink.exceptions.CommsException (or other error)  mmtune 50% of the time
4th time  in case of mmeowlink.exceptions.CommsException (or other error)  mmtune 25% of the time
5th time  (or more) in case of mmeowlink.exceptions.CommsException (or other error)  mmtune 15% of the time
if pump comms is succesfull reset the counter.

I would not implement that in a loop, but with a seperate mechanism outside the pump loop (e.g. some `/tmp` file or a python/nodejs daemon that saves this state in memory).

**Comment by PieterGit** [comment] 2017-07-04 21:19
My battery powering the UART port was exhaused.  Rig battery was still at 84%.

I think I know a way to reproduce this:
- use Dexcom G4 connected to USB
- remove powersupply on the UART port 
- insert powersupply on the UART port 
- (most of the times this causes `lsusb -99` errors, that require a reboot)
- reboot
- check pump loop logfile, and voila:
```
Starting supermicrobolus pump-loop at Tue Jul  4 23:12:02 CEST 2017 with 28 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs
mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
Aborted supermicrobolus pump-loop with exitcode 1 at Tue Jul  4 23:13:05 CEST 2017
Sleeping 3;
``` 

Pump is really near rig, so it's a disturbed rig-pump communication thing. The mmtune workaround fixes the problem.

**Comment by Bender1061** [comment] 2017-07-05 00:53
I'm thinking we might want to put something like
```
if [ ! -f "monitor/mmtune.json" ]; then
		mmtune
fi
```
at the beginning of Preflight
so when first starting, you would not have to wait for that 25% of the time before things actually start working. 
sure it's only needed once at the beginning. I see this type of thing a lot, cause I always delete the aps directory before I do anything. I actually normally do something like this
```
cd  && rm -r johnopenaps && cd ~/src/ && rm -r oref0 && mkdir -p ~/src; cd ~/src && git clone -b dev git://github.com/openaps/oref0.git || (cd oref0 && git checkout dev && git pull) && cd ~/src/oref0/ && npm run global-install
```

**Comment by Bender1061** [comment] 2017-07-05 01:38
So another change I've made that seems to be helping is undr Preflight.
```
function preflight {
    if [ ! -f "monitor/mmtune.json" ]; then
		mmtune
    fi
    # only 515, 522, 523, 715, 722, 723, 554, and 754 pump models have been tested with SMB
    ( openaps report invoke settings/model.json || openaps report invoke settings/model.json ) 2>&1 >/dev/null | tail -1 \
    && egrep -q "[57](15|22|23|54)" settings/model.json \
    && echo -n "Preflight OK. "
}
```
I have it running the settings/model twice if it fails.
This is kind of a theme I've noticed.  for some unknown reason sometimes a command to the pump fails, and if you run it again right away it works.

I'm starting to wonder if this is a theme with a lot of the errors I've seen. kind of liked the clock-zoned errors and the like. not sure on that, but it's possible.

Now I'm running a 723 with 2.4A firmware.

**Comment by Bender1061** [comment] 2017-07-05 01:45
But @scottleibrand changes with #523 does not seem to have made much differences for me. I'm thinking of trying Dev with the changes I mentioned above and see if that helps at all.

**Comment by PieterGit** [comment] 2017-07-05 21:34
I had success with todays version of https://github.com/openaps/oref0/issues/523 !

**Comment by Bender1061** [comment] 2017-07-06 00:04
Yes I agree, that fixed my issues.

**Comment by scottleibrand** [comment] 2017-07-06 00:22
Cool.  I'll close this out then.  Please reopen or open a new issue if you (still) see anything (else).

**Closed by scottleibrand** 2017-07-06 00:22 UTC
