### ISSUE TITLE
'Unary operator expected' errors reported

### ISSUE THREAD

**Issue by N3FM** [openaps/oref0#1076] opened 2018-07-29 23:41 UTC
Errors are reported for these lines in oref0-pump-loop.sh. "Unary operator expected' errors are returned for the two 'test' lines below: 

`
# Refresh pumphistory etc.
function refresh_pumphistory_and_meal {
    retry_return timerun openaps report invoke monitor/status.json 2>&3 >&4 | tail -1 || return 1
    echo -n Ref
    ( grep -q "model.*12" monitor/status.json || \
         test $(cat monitor/status.json | json suspended) == true || \
         test $(cat monitor/status.json | json bolusing) == false ) \
         || { echo; cat monitor/status.json | jq -c -C .; return 1; }
`

I'd suggest checking the '==' entries throughout...

**Comment by scottleibrand** [comment] 2019-10-21 00:16
Is this still an issue since 5cb8f9227bf175da183794d70027adc372e46827 replaced `json` with `jq` there?

**Comment by N3FM** [comment] 2019-10-21 02:52
I'm currently unable to test...

I believe this was related to the use of == instead of =  . Please review
intent of those two commands.

Bob N3FM

**Comment by cluckj** [comment] 2019-10-21 19:53
:+1: It's not returning this error on my x12 setup, and I haven't seen it on my x22 either.

**Comment by scottleibrand** [comment] 2019-10-21 19:57
Ok, thanks. I’ll close the issue then. I believe == is the intended behavior (make sure the two things are equal).

**Closed by scottleibrand** 2019-10-21 19:57 UTC
