### ISSUE TITLE
COB=0 issue with BolusWizard with carbs and bolus

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#587] opened 2017-08-09 22:07 UTC
I'm seeing `COB=0` in the pump log, when I don't expect it.  Example:
The following boluseses were made with the pump BolusWizard. 
The rig is offline at that moment because of empty battery of phone.

```
18:44. Carbs=33. Insulin=2.3U
18:49. Carbs=15. Insulin=1U 
19:24. Carbs=65. Insulin=3.4U
```

The pump loop reports `COB=0` from 18:30:03 until 20:10:03. Insulin is correctly administrated. I think the COB issue resolved when the connection to Nightscout resolved again (because phone was uploading again).

With `egrep 'Starting supermicrobolus pump-loop|smb-suggested.json.*COB' pump-loop.log  | sed -e 's/.*smb-suggested.*\(COB: [^,]*\).*$/\1/g' | less -r` I see:

```
Starting supermicrobolus pump-loop at Tue Aug 8 18:30:03 CEST 2017 with 17 second wait_for_silence:
COB: 0
... [ continues for 21 pump runs / 100 minutes ]
Starting supermicrobolus pump-loop at Tue Aug 8 20:10:03 CEST 2017 with 29 second wait_for_silence:
COB: 0
Starting supermicrobolus pump-loop at Tue Aug 8 20:18:03 CEST 2017 with 14 second wait_for_silence:
COB: 64
COB: 28
Starting supermicrobolus pump-loop at Tue Aug 8 20:23:02 CEST 2017 with 12 second wait_for_silence:
COB: 59
COB: 54
Starting supermicrobolus pump-loop at Tue Aug 8 20:27:02 CEST 2017 with 15 second wait_for_silence:
COB: 54
Starting supermicrobolus pump-loop at Tue Aug 8 20:31:03 CEST 2017 with 8 second wait_for_silence:
COB: 50
``` 

I don't see any weird errors in the pump log.  As discussed with @scottleibrand I expect to see these carbs counted. I-to-b discussion link: https://gitter.im/nightscout/intend-to-bolus?at=598b7eb5c101bc4e3a02cb67

@scottleibrand : any advice how to dig further?

**Comment by PieterGit** [comment] 2017-08-09 22:18
One more detail: this was with a dev rig, with oref1. I just disabled autotune the day before, but forgot to create a new autotune directory, so SMB's were not possible (because of `Warning: Autotune has not been run. All microboluses will be disabled until you manually run autotune `). So it's a oref1 pump loop, with SMB disabled because of a missing autotune directory.

**Comment by scottleibrand** [comment] 2017-08-09 22:29
If this just showed COB: 0 for a single pump run, it was likely a transient error refreshing something, and likely wouldn't be easy to reproduce.  At this point we know there are some bugs with COB calculation, but until we figure out how to reproduce them, we're not making much progress on troubleshooting, other than the work @sulkaharo is doing to build unit tests.

**Comment by PieterGit** [comment] 2017-08-09 23:28
No it's showed `COB=0` for 21 pump runs / 100 minutes.  Made that clearer in the issue description.

I'll dig into it later. I'm suspecting something wrong near here:
https://github.com/openaps/oref0/blob/dev/lib/meal/history.js#L54-L55
and that the carbs are mistakenly seen as duplicates.

Can it be that timezoned and UTC  / non-timezoned timestamps are compared here?
https://github.com/openaps/oref0/blob/dev/lib/meal/history.js#L7

**Comment by PieterGit** [comment] 2017-08-10 21:45
Definitely something wrong with `ns-loop`.  I'm seeing:  
```
reporting monitor/carbhistory.json
skipping bolus wizard entry with 16 g carbs and no insulin` when there was a bolus.
```

Shouldn't https://github.com/openaps/oref0/blob/a492c5eb04f8d70888b7c672321edac1736c8471/lib/meal/history.js#L55 (master version) be something like:

```
    // don't enter the treatment if there's another treatment with the same exact timestamp
            // to prevent duped carb entries from multiple sources
            if (!arrayHasElementWithSameTimestampAndProperty(mealInputs,current.timestamp,"carbs")) {
                if (arrayHasElementWithSameTimestampAndProperty(mealInputs,current.timestamp,"bolus")) {
                    temp.bolus = current.insulin;
                    mealInputs.push(temp);
``` 

I noticed that the `temp.bolus` is never set for this case of `BolusWizard` entries.
@oskarpearson @scottleibrand : please advice what's the suggested fix

**Comment by scottleibrand** [comment] 2017-10-09 02:14
I'm not sure what the fix is here.  I think in order to proceed we'll need to create a repro case, possibly by capturing the data files used by oref0-meal (monitor/pumphistory-merged.json settings/profile.json monitor/clock-zoned.json monitor/glucose.json settings/basal_profile.json monitor/carbhistory.json) when the problem is occurring, so we can test out possible fixes.

**Comment by scottleibrand** [comment] 2017-11-05 03:41
This might be related to / fixed by https://github.com/openaps/oref0/issues/709#issuecomment-341946372

Have you seen any more instances of this, or should we close it in favor of #709 ?

**Comment by danamlewis** [comment] 2018-04-16 21:26
Closing in favor of #709

**Closed by danamlewis** 2018-04-16 21:26 UTC
