### ISSUE TITLE
wlan0 service stops with more than one wifi network in wpa-supplicant file

### ISSUE THREAD

**Issue by Kdisimone** [openaps/oref0#648] opened 2017-09-09 02:37 UTC
Two people now have had their rigs suddenly stop working with the same error.  

Rig just stops connecting to wifi networks it had previously had no problems with.  No changes in the rig being done at the time of the error happening.  Nothing to obviously identify why the error started.

The error message that comes up when `ifup wlan0` is this...

```
wpa_supplicant: /sbin/wpa_supplicant daemon failed to start  
run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1  
Failed to bring up wlan0.
```

I did find this on google that is same issue.  Person identified it was using Jubilinux with Edison as well.  https://communities.intel.com/thread/110485

The only solution so far has been to comment out all but one wifi network (in wpa-supplicant), run `ifup wlan0` and then reboot the rig.  Then the person can go back in with `edit-wifi` and remove the hashtags for the other networks.  

The first person did this fix and the rig worked for a week or so before the error reappeared.
The second person just got the error tonight, 14 days after the first person reported the error to me.

**Comment by Kdisimone** [comment] 2017-09-09 02:40
This was the wpa-supplicant file that wasn't working
```
root@devon1:~# cat-wifi
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="308 Burt Street"
    psk="xxxx"
}
network={
    ssid="Newell Broadcasting"
    psk="xxxx"
}
network={
    ssid="Solberg"
    psk="xxxx"
}
network={
    ssid="TP-Link_D6EA_5G"
    psk="xxxx"
}
network={
    ssid="Baker Wireless Network WiFi"
    psk="xxxx"
}
network={
    ssid="Rig2"
    psk="xxxx"
}
```

**Comment by Kdisimone** [comment] 2017-09-09 17:34
The wlan0 service was able to be restarted once the wpa-supplicant file was reduced to one network (either through deleting the other networks or by commenting out with # the other networks).

```
root@devon1:~# cat-wifi
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="308 Burt Street"
    psk="xxxx"
}
#network={
#    ssid="Newell Broadcasting"
#    psk="xxxx"
#}
#network={
#    ssid="Solberg"
#    psk="xxxx"
#}
#network={
#    ssid="TP-Link_D6EA_5G"
#    psk="xxxx"
#}
#network={
#    ssid="Baker Wireless Network WiFi"
#    psk="xxxx"
#}
#network={
#    ssid="Rig2"
#    psk="xxxx"
#}
```

**Comment by lsandini** [comment] 2017-09-22 09:58
I would add priority numbers for the various networks in the wpa_supplicant.conf file, especially if they are covering same areas. I have 2 APs at home on 2 floors, and my rig switches from one to the other when moving inside the house. Both APs are connected to the same switch/router, so I always get the same IP (linked to my rig's MAC address). Both APs can be seen all around the house, but each one is stronger on its own floor.
Before adding the priority numbers I kept losing my wifi and my rig fell back to BT tethering. Highest priority = preferred network. Hope this helps.

network={
    ssid="308 Burt Street"
    psk="xxxx"
    priority=10 
}
network={
    ssid="Newell Broadcasting"
    psk="xxxx"
    priority=5
}

**Comment by Kdisimone** [comment] 2017-09-22 13:57
@lsandini yup, we tried adding priorities to the networks and that solution didn’t end up resolving the problem. Originally we had thought it did, but the problem recurred even with priorities. Sorry I didn’t indicate that originally in the post...

**Comment by sulkaharo** [comment] 2017-09-22 13:59
Unlikely but possible this is BroadPwn related

**Comment by sulkaharo** [comment] 2017-09-22 14:21
Have you checked if the disk is full on these devices? I recall Edison network switching stops working if the disk is full.

**Comment by scottleibrand** [comment] 2017-10-09 01:59
To proceed with troubleshooting this, I think we need to collect a copy of the exact wpa_supplicant.conf file that causes issues, place it on another rig, and test whether we can reproduce the problem.  In order to avoid making any changes to the wpa_supplicant.conf, we can test by changing a phone hotspot name to be the same as one of the configured networks.

**Comment by woodduckie** [comment] 2017-10-23 00:33
I too am having trouble with reconnecting to wifi after reboot or moving away from home wifi.  I have just commented out all but my primary wifi network & am able to reconnect with reboot.

`root@JacobAPS:~# ifup wlan0
wpa_supplicant: /sbin/wpa_supplicant daemon failed to start
run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1
Failed to bring up wlan0.
`

During reboot, I also see an error of "Failed to start Hostname Service.

`         Starting Hostname Service...
[FAILED] Failed to start Hostname Service.
See 'systemctl status systemd-hostnamed.service' for details.
         Starting Load/Save RF Kill Switch Status of rfkill3...
`

I'm happy to share copies of wpa_supplicant.conf, though I just got started a couple of days ago & they're simply additions to the original.  I'm using the edison & explorer board from late 2016 if that matters...

**Comment by Kdisimone** [comment] 2017-11-24 18:02
Another three people have come to me with troubleshooting issues where this was the issue. Just FYI. Problem persists

**Comment by scottleibrand** [comment] 2017-11-24 18:53
Have you been able to reproduce it yet with known-good wifi networks?

**Comment by usaf167aw** [comment] 2017-12-14 03:45
I am now having this problem I would be willing to send any information needed to see where this error is coming from, and whats causing it.

**Comment by scottleibrand** [comment] 2017-12-14 04:01
You probably have a syntax error in your wpa_supplicant.conf.  It's much easier to troubleshoot those if you don't have to redact the network names and passwords: if you're comfortable doing so, feel free to PM me on Gitter with the complete files, working and non-working.

**Comment by Kdisimone** [comment] 2017-12-14 04:03
@scottleibrand I quadruple checked the ones that I was helping back when I started this.  No typos (and I swear I don't make that statement lightly in the troubleshooting world).  I spent probably 35 minutes several times literally character by character.  And we copy and pasted from one working rig, to that troubled rig...problem persisted.  It's a bugger.

**Comment by scottleibrand** [comment] 2017-12-14 04:06
@Kdisimone have you ever reproduced this on your own rigs at your own house (in a known-good working wifi environment)?  I think one of the next steps is to get a fully reproducible setup: for example, being able to change an iPhone's hotspot name, configure that and get it working on a rig, and then show how adding a second wifi config breaks the previously working one.  I only expect that to  be possible if there's some sort of syntax error, but we'll see.

**Comment by usaf167aw** [comment] 2017-12-14 04:21
@scottleibrand I will give you whatever you are looking for. Just need to let me know how to get it. I’m not quite fluent in Linux just yet.

**Comment by scottleibrand** [comment] 2017-12-14 04:23
Ok, hit me up on Gitter (https://gitter.im/scottleibrand) and I'll walk you through it.

**Comment by usaf167aw** [comment] 2017-12-14 14:16
I had another thought this morning.. what are the chances that this happens on both rigs I have? One was pre flashed when I bought it. The other I had to flash.

**Comment by usaf167aw** [comment] 2018-01-09 23:56
just thought I would update on what me and Scott were about to find. When I was using the command "edit-wifi" it wasn't saving correctly when I was editing using nano. If I went into " vi /etc/wpa_supplicant/wpa_supplicant.conf " and did I then saved with ESC and :wq. It must have wrapped correctly and then mine started to work correctly with multiple WiFi in the supplicant file.

**Comment by Kdisimone** [comment] 2018-02-14 03:34
@scottleibrand posting an update here...I suspect, after more time seeing people's wifi failures, that the dnsmasq service failure message at boot is an indication of the root failure.  The rigs with the wifi connections failing seem to have that message appear.  Reflashing the rigs brings the service back on and wifi wlan0 starts fine again.

**Comment by scottleibrand** [comment] 2018-02-15 03:10
I wonder if this is somehow related to dnsmasq being installed but always stopped (unless you're using the local-only hotspot)?  https://github.com/openaps/oref0/blob/master/bin/oref0-online.sh#L158-L170  That doesn't explain why only a minority of people have issues, though.  I agree that trying `apt-get remove --purge dnsmasq and then apt-get install dnsmasq` the next few times people experience this would be a good next step.

**Comment by Kdisimone** [comment] 2018-02-25 20:37
@scottleibrand what would happen (what would impacts be) if someone opted to comment out those lines?

**Comment by scottleibrand** [comment] 2018-02-25 20:55
Just commenting out the stop_hotspot function would cause the local-only hotspot to continue running even when it should be acting as a wifi client, so that's the opposite of what you're trying to accomplish.  Sounds like what you want to do is completely prevent the hostapd and dnsmasq stuff from getting installed in the first place?  That's in oref0-setup, but I haven't looked at how to do so cleanly.

**Comment by brmccollum** [comment] 2018-03-12 02:46
This is my second rig that has had the problem.  The first one is collecting dust in a box.  I tried the priority suggestion above and had no success.  I then deleted all but one wifi network and that too didn't help.  Then after 3 days of staring at this I noticed my config file had an extra piece of information in it that the above examples did not.

```ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev update_config=1

network={
  ssid="HOME-E4AA-2.4"
  psk="xxx" 
}```

I deleted the ```update_fonfig=1``` to match the examples above and then ran ```ifup wlan0``` and then ```reboot```.  That seemed to do the trick.  My rig is working again.

**Comment by danamlewis** [comment] 2018-04-11 21:45
Seeing a number of examples where `update_config=1` ends up being added to line 1 somehow. Deleting that fixes it. Unclear if that particular thing is related to the previous issues, because I don't see it in @Kdisimone's earliest examples of this thread, but I've seen this be the issue in the last ~5 I've seen in the past two weeks. @tim2000s also confirmed today his rigs don't have that, so help welcome from someone figuring out what command or file or editing process is adding this to the file and potentially causing many of these wifi-related issues. If we figure out what is adding it, we can either write a fix to stop it from adding, or run a check and delete it if it pops up.

**Comment by Kdisimone** [comment] 2018-04-11 21:56
I think of the the best things would be to change the edit-wifi alias to use vi instead of nano. It may not solve everything, but it would help. While in screen mode (which is how a lot of initial setup is done), nano is awful at justification errors. Vi keeps lines better separated

**Comment by scottleibrand** [comment] 2018-04-11 21:56
According to https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf and https://wiki.archlinux.org/index.php/WPA_supplicant, the `update_config=1` makes it possible for tools like `wpa_cli`, a command line tool which can be used to configure wpa_supplicant, to update the config file.  I can't see from any of the documentation how its presence should affect anything, but since we don't use wpa_cli/wpa_gui, it shouldn't hurt to remove it either.

**Comment by scottleibrand** [comment] 2018-04-11 21:57
I agree no one should ever be using `nano` over console.  If people tend to do `edit-wifi` over console instead of over SSH, then I agree it should use `vi`.

**Comment by danamlewis** [comment] 2018-04-11 22:00
K, just updated that in https://github.com/openaps/oref0/pull/962 for the fix-log-rotate patch branch. But, we'll still need to figure out how `update_config=1` is being added and where to resolve that issue, because people aren't manually inputting that...

**Comment by Kdisimone** [comment] 2018-04-11 22:02
Pretty sure that (update config) is bootstrap addition. I usually only see that in rigs that I bootstrap

**Comment by danamlewis** [comment] 2018-04-11 22:03
Not sure - @tim2000s has rigs built with bootstrap that doesn't have it. But, he has another rig so he's going to test current bootstrap and see if that's the case.

**Comment by Kdisimone** [comment] 2018-04-11 22:35
I’ve used Mac. I think Tim is mostly windows?  I wonder if that makes a difference?

**Comment by tim2000s** [comment] 2018-04-12 15:53
Ran a fresh bootstrap last night - all mine are done from Mac. The wpa_supplicant.conf does not contain the update_config=1. 

It would be good to know which version of Jubilinux people have installed on rigs. Mine are all version 0.2.0. 

My suspicion is that 0.3.0 contains the wpa cli client, and that’s not available in 0.2.0, so the wpa_supplicant.conf contains the required config to allow it to work. 

0.3.0 became the “latest stable” version in late November/early december which is about the time we started to see these Wi-fi issues occurring. I need to flash another Edison with 0.3.0 to see if this holds out.

**Comment by tim2000s** [comment] 2018-04-12 15:54
It could also mean that the changes in 0.3.0 might be affecting Wi-fi switching. Just a thought.

**Comment by Kdisimone** [comment] 2018-04-12 16:13
I don’t think the jubilinux is that. I use an older version too (the April one...0.2.0 or 0.1.0?)

**Comment by lsandini** [comment] 2018-04-12 17:34
I had the issue on only one rig, and I cannot reproduce it anymore. (Probably reflashed it at some point). All my rigs are jub 0.2.0.

**Comment by danamlewis** [comment] 2018-04-12 20:15
It was being added with bootstrap and then likely changed/messing up elsewhere; I removed it via https://github.com/openaps/oref0/commit/18ba4f2b5ec62c40fd2d83b9661be127fa58078b and it's part of the changes of fix-log-rotate that need testing (https://github.com/openaps/oref0/pull/962). Please report back if you test with this fix-log-rotate branch and if this resolves the problem of update_config=1 appearing and moving around and causing issues.

**Comment by tim2000s** [comment] 2018-04-24 19:59
Just been digging into this a bit further given the comments in Looped today. Looks like it might be a different version issue. When I do uname -r on my rigs where I don't have `update_config=1` in wpa_supplicant.conf, `uname -r` returns `3.10.17` Where I do have it, `uname -r` returns `3.10.98`. The 3.10.98 rigs are ones I've bootstrapped. The other two aren't.

What I think is happening is that the bootstrap is installing a load of update packages (hence the different kernel version), which includes an updated wpa_supplicant.conf including that variable, as someone realised that the earlier one wasn't allowing `wpa_cli` to properly set wireless lans . Hence my older rigs have older, perhaps less secure, kernels, but don't suffer the issue. Removing it also seems to fix the bluetooth connectivity issue for some users.

**Comment by tim2000s** [comment] 2018-06-13 10:05
Been running 0.7.0-dev with bootstrapped Linux and LineageOS 15.1 today. Rock solid Bluetooth comms on the phone/rig. Need to test Wi-fi switching.

**Comment by tim2000s** [comment] 2018-06-14 05:44
Interesting one here that would need someone else to check. When I ran the Oref0-setup it undertook various apt-get updates. I think one of them may have reinstated the update_config=1 entry in the wpa_supplicant.conf file after I’d removed it. 

Would need to rerun and double check, but removal of that statement has completely fixed Wi-fi and BT PAN switching.

**Comment by endafarrell** [comment] 2018-06-21 18:44
Still on 0.6.0, and I've developed this problem too.

I was away from home for two weeks, tried joining the wifi where I was (via adding wifi details to the ``/etc/wpa_supplicant/wpa_supplicant.conf``), the wifi was very poor, in the end I just turned wifi off (by un-editing the ``/etc/wpa_supplicant/wpa_supplicant.conf``).

Now home, the rig does not join my known-to-be-good wifi, and removing other entries in ``/etc/wpa_supplicant/wpa_supplicant.conf`` does not help. There is no ``update_config=1`` entry.

Running ``ifconfig wlan0 up`` returns ``SIOCSIFFLAGS: Operation not possible due to RF-kill``. 

Running ``rfkill list`` shows:

```
0: bcm43xx Bluetooth: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: yes
        Hard blocked: no
2: brcmfmac-wifi: Wireless LAN
        Soft blocked: no
        Hard blocked: no
3: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
```

The rig's kernel _seems to_ have blocked wifi and this _seems to_ be persistent across restarts (I had a few ``reboot``s along the way.

After running ``rfkill unblock wifi``, re-running ``rfkill list`` shows:

```
0: bcm43xx Bluetooth: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
2: brcmfmac-wifi: Wireless LAN
        Soft blocked: no
        Hard blocked: no
3: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
```

Now, running ``ifconfig wlan0 up`` returns without error, and ``ifconfig wlan0`` how shows a valid ``HWaddr`` (previously it was ``00:00:00:00:00:00``:

```
wlan0     Link encap:Ethernet  HWaddr fc:db:b3:a1:ad:fa
          inet addr:192.168.1.90  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:225 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5085 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:66528 (64.9 KiB)  TX bytes:824480 (805.1 KiB)
```

Once the ``network`` loop runs again (one minute later) my ``tail -f /var/log/openaps/network.log`` shows:

```
Starting oref0-online at Thu Jun 21 20:36:02 CEST 2018.
At Thu Jun 21 20:36:02 CEST 2018 my wifi network name is Kociak
At Thu Jun 21 20:36:02 CEST 2018 my local wifi IP is: 192.168.1.90
At Thu Jun 21 20:36:02 CEST 2018 my Bluetooth PAN is not connected
At Thu Jun 21 20:36:02 CEST 2018 my public IP is: 95.91.215.238
At Thu Jun 21 20:36:03 CEST 2018 my local hotspot is not running (and not enabled in preferences.json)
Finished oref0-online at Thu Jun 21 20:36:03 CEST 2018.
```

All of these values are good and correct. Nightscout is being updated without needing BT.

To test that this persists across ``reboot``s, I ``reboot``ed and all remained well.

My *guess* is that my rig's poor wifi while I was away was "bad enough" (whatever that means) that the kernel thought that the wifi hardware needed to be disabled. ``rfkill unblock wifi`` seems a less invasive troubleshoot than reflashing, but of course YMMV and as with everything, won't solve all wifi-related problems, but this worked for me.

**Comment by Alzibiff** [comment] 2018-06-21 19:01
Thank you Jane - I will take a look.
See you on Sunday :-)

Alan

**Comment by tim2000s** [comment] 2018-06-21 19:17
@endafarrell Have you checked your wpa_supplicant.conf file for the ‘update_config=1’ phrase?

I expect that will be there. If you delete it it will allow the connection across different Wi-fi networks and Bluetooth.

**Comment by endafarrell** [comment] 2018-06-21 20:45
Hi @tim2000s - I'm completely certain that there is/was no ``update_config=1`` entry in my ``/etc/wpa_supplicant/wpa_supplicant.conf`` (as mentioned at the end of the 3rd paragraph from my entry above). 

There /was/ a time when there was such an entry - I have a backup from many months ago where it was the sole entry on the second line - but I removed it a couple of months ago (when I added a new work SSID) so it wasn't in play over the last 3 weeks.

**Comment by tim2000s** [comment] 2018-06-21 23:48
Have you checked back since you installed 0.6.0/1 ? It would be good to check whether the downloads in the setup script puts it back again.

**Comment by endafarrell** [comment] 2018-06-22 21:06
@tim2000s  I'm not _entirely_ sure I understand your question, but:

- I've only had to install the rig once. That was with 0.6.0: I haven't needed to update nor re-flash (lucky me). That was Nov 2017. I have yet to update to 0.7, I missed 0.6.1, I am still running 0.6.0 (i have been busy).
- I had "fun" getting my work WiFi set up, and, I have added/removed multiple networks over the last 6 months or so. 
- I do have BT tethering too set-up for when I am "out and about" and the hand-over between them works very well.
- ``update_config=1`` _was_ part of my conf - but I cannot tell/remember where it came from. It might have been the initial install, it might have been me copying WiFi setup instructions from the docs (especially getting my work LEAP settings correct)
- Re: "whether the downloads in the setup script puts it back again" - I don't believe I've ever re-run the setup scripts/bootstrapping scripts. I do happily change my conf files (manually), reboot, test to see that they work - but it does mean that I don't have a reliable log of how edits came to be made.

/e

ps: twice I was logged in from a phone over BT re-editing the wifi conf in ``vi`` while adding new networks ... who knows when I changed what.

pps: I think though that adding ``rfkill unblock wifi`` to the troubleshooting is still worth considering, irrespective of how any ``update_config=1`` ended up in the conf. I don't think you're suggesting otherwise, but I thought I'd reiterate that again.

**Comment by danamlewis** [comment] 2019-11-10 20:01
Per https://github.com/openaps/oref0/issues/648#issuecomment-380931023, have not seen reports of this re-occurring with 0.7.0 or in the last 1.5y so closing; please re-open with a comment and details if you see this occurring on a rig updated to the latest.

**Closed by danamlewis** 2019-11-10 20:01 UTC
