### ISSUE TITLE
Double COB 

### ISSUE THREAD

**Issue by Kdisimone** [openaps/oref0#387] opened 2017-02-06 19:27 UTC
I have yet to narrow down the when or how that this is happening, but some carb entries made using the pump (seen this on 722 and 723 pumps so far) have been read as double and used by OpenAPS as double...so far these have been entered using pump bolus wizard and have not been "backed out" of before bolus.

If there's some suggestions that you have to help gather useful info (command lines to run? and when?) that would help troubleshoot this...I'm happy to implement.  

Sometimes the double COB sticks around affecting temp basals (first screen shot), and other times I've seen it resolve (second screen shot did eventually resolve the COB to the correct number, unsure of time frame, but probably 15-20 min?)

![117_-3_](https://cloud.githubusercontent.com/assets/12402160/22662891/82230cba-ec5f-11e6-889e-80ec4044ac0d.jpg)

![140_-3__](https://cloud.githubusercontent.com/assets/12402160/22662963/c4978896-ec5f-11e6-90e9-6e0628c28bfd.jpg)

**Comment by Kdisimone** [comment] 2017-02-06 19:44
Looking at this one more in detail....over time, here's the info from the pills

You can see the problem start.  The careportal somehow has a double COB already.  OpenAPS pill during this time is reporting COB=0.  Shows carbs entered at 9:22
![112_-5_](https://cloud.githubusercontent.com/assets/12402160/22663382/3a61fd26-ec61-11e6-8b52-90c222a91b8a.jpg)

At 9:25, same situation.  OpenAPS pill showing COB=0, NS COB pill showing same doubled carbs.
![112_-5_ 2](https://cloud.githubusercontent.com/assets/12402160/22663399/4fe79fe8-ec61-11e6-88cb-ea870d4d0857.jpg)

At 9:28, OpenAPS still COB=0
![112_-5_ 3](https://cloud.githubusercontent.com/assets/12402160/22663469/8bf634b8-ec61-11e6-8a3d-7449dc3f1b0d.jpg)

At 9:30, OpenAPS pill starts to show the problem
![112_-5_ 4](https://cloud.githubusercontent.com/assets/12402160/22663480/978a519c-ec61-11e6-9622-b122739f6cf4.jpg)

**Comment by cjo20** [comment] 2017-02-06 19:51
I think this is just an issue with entering carb details twice. A Bolus Wizard record is created when you enter BG and carbs (when the recommendation is made), so if you back out of it the "BolusWizard" record is already there. This means that if you enter it again, you get a second record. 

These bolus wizard records are separate from bolus records, which are created when the bolus is actually delivered.

The easiest way to avoid this problem is to only enter carbs in to the bolus wizard once, and to not back out of it once you've started. It's difficult to remove these records automatically, because you can't tell the difference between a mistaken double entry, and someone putting in carbs and deliberately not bolusing.

**Comment by Kdisimone** [comment] 2017-02-06 20:01
My concern is that these are not where someone is backing out of bolus wizard.  They are following the bolus wizard all the way through.  Enter the bolus wizard, they give no BG, they enter carbs, they get the recommended bolus and confirm to deliver.

What about that would cause a double entry?

**Comment by danamlewis** [comment] 2017-02-06 20:04
@Kdisimone it sounds like most of these self resolve a few minutes later, too - can you confirm the typical time period where COB re-normalizes, or is this not always happening in every case?

**Comment by scottleibrand** [comment] 2017-02-06 20:06
Have you looked at the Nightscout treatments API (https://yournightscout/api/v1/treatments.json) to see what is actually present in the DB?  Could you share a copy-paste excerpt from there, or PM one of us the Nightscout URL to take a look?

**Comment by Kdisimone** [comment] 2017-02-06 20:10
This one today is ongoing.  Not self resolving

![111__3_](https://cloud.githubusercontent.com/assets/12402160/22664373/417f314c-ec65-11e6-8e6e-a1a4ac38ac53.jpg)

I will pull up the treatments API now

**Comment by Kdisimone** [comment] 2017-02-06 20:14
this covers the time frame of the 9:22 bolus today

```
{"_id":"5898b847bd4bf2dc76c9dfc8","duration":30,"raw_duration":{"_type":"TempBasalDuration","_description":"TempBasalDuration 2017-02-06T09:48:48 head[2], body[0] op[0x16]","timestamp":"2017-02-06T09:48:48-08:00","_body":"","_head":"1601","duration (min)":30,"_date":"30b0094611"},"timestamp":"2017-02-06T09:48:48-08:00","absolute":0.575,"rate":0.575,"raw_rate":{"_type":"TempBasal","temp":"absolute","_description":"TempBasal 2017-02-06T09:48:48 head[2], body[1] op[0x33]","timestamp":"2017-02-06T09:48:48-08:00","_body":"00","_head":"3317","rate":0.575,"_date":"30b0094611"},"eventType":"Temp Basal","medtronic":"mm://openaps/mm-format-ns-treatments/Temp Basal","created_at":"2017-02-06T09:48:48-08:00","enteredBy":"openaps://medtronic/723","carbs":null,"insulin":null},{"_id":"5898b439bd4bf2dc76c9dfc2","duration":30,"raw_duration":{"_type":"TempBasalDuration","_description":"TempBasalDuration 2017-02-06T09:28:48 head[2], body[0] op[0x16]","timestamp":"2017-02-06T09:28:48-08:00","_body":"","_head":"1601","duration (min)":30,"_date":"309c094611"},"timestamp":"2017-02-06T09:28:48-08:00","absolute":1.6,"rate":1.6,"raw_rate":{"_type":"TempBasal","temp":"absolute","_description":"TempBasal 2017-02-06T09:28:48 head[2], body[1] op[0x33]","timestamp":"2017-02-06T09:28:48-08:00","_body":"00","_head":"3340","rate":1.6,"_date":"309c094611"},"eventType":"Temp Basal","medtronic":"mm://openaps/mm-format-ns-treatments/Temp Basal","created_at":"2017-02-06T09:28:48-08:00","enteredBy":"openaps://medtronic/723","carbs":null,"insulin":null},{"_id":"5898b2aebd4bf2dc76c9dfba","duration":30,"raw_duration":{"_type":"TempBasalDuration","_description":"TempBasalDuration 2017-02-06T09:25:32 head[2], body[0] op[0x16]","timestamp":"2017-02-06T09:25:32-08:00","_body":"","_head":"1601","duration (min)":30,"_date":"2099094611"},"timestamp":"2017-02-06T09:25:32-08:00","absolute":0.575,"rate":0.575,"raw_rate":{"_type":"TempBasal","temp":"absolute","_description":"TempBasal 2017-02-06T09:25:32 head[2], body[1] op[0x33]","timestamp":"2017-02-06T09:25:32-08:00","_body":"00","_head":"3317","rate":0.575,"_date":"2099094611"},"eventType":"Temp Basal","medtronic":"mm://openaps/mm-format-ns-treatments/Temp Basal","created_at":"2017-02-06T09:25:32-08:00","enteredBy":"openaps://medtronic/723","carbs":null,"insulin":null},{"_id":"5898b2aebd4bf2dc76c9dfbb","duration":0,"bolus":{"_type":"Bolus","_description":"Bolus 2017-02-06T09:22:04 head[8], body[0] op[0x01]","timestamp":"2017-02-06T09:22:04-08:00","_body":"","appended":[{"_type":"UnabsorbedInsulinBolus","_description":"UnabsorbedInsulinBolus unknown head[17], body[0] op[0x5c]","_body":"","_head":"5c11105d04066704167b0414b11416d914","data":[{"amount":0.4,"age":93},{"amount":0.15,"age":103},{"amount":0.55,"age":123},{"amount":0.5,"age":433},{"amount":0.55,"age":473}],"_date":""}],"programmed":1.05,"duration":0,"amount":1.05,"unabsorbed":0.6,"_head":"01002a002a001800","type":"normal","_date":"0496490611"},"timestamp":"2017-02-06T09:22:03-08:00","created_at":"2017-02-06T09:22:03-08:00","carbs":14,"ratio":"13","wizard":{"_type":"BolusWizard","bg":0,"_description":"BolusWizard 2017-02-06T09:22:03 head[2], body[15] op[0x5b]","timestamp":"2017-02-06T09:22:03-08:00","_body":"0e500082645a00002a000000002a5a","appended":[{"_type":"UnabsorbedInsulinBolus","_description":"UnabsorbedInsulinBolus unknown head[17], body[0] op[0x5c]","_body":"","_head":"5c11105c04066604167a0414b01416d814","data":[{"amount":0.4,"age":92},{"amount":0.15,"age":102},{"amount":0.55,"age":122},{"amount":0.5,"age":432},{"amount":0.55,"age":472}],"_date":""}],"bg_target_high":90,"sensitivity":100,"carb_input":14,"carb_ratio":13,"food_estimate":1.05,"unabsorbed_insulin_total":0,"correction_estimate":0,"bg_target_low":90,"_head":"5b00","bolus_estimate":1.05,"_date":"0396090611"},"eventType":"Meal Bolus","insulin":1.05,"notes":"Normal bolus with wizard.\nProgrammed bolus 1.05\nDelivered bolus 1.05\nPercent delivered:  100%\nFood estimate 1.05\nCorrection estimate 0\nBolus estimate 1.05\nTarget low 90\nTarget high 90\nHypothetical glucose delta -105","medtronic":"mm://openaps/mm-format-ns-treatments/Meal Bolus","enteredBy":"openaps://medtronic/723"},{"_id":"5898b2aebd4bf2dc76c9dfbc","carbs":14,"ratio":"13","wizard":{"_type":"BolusWizard","bg":0,"_description":"BolusWizard 2017-02-06T09:21:18 head[2], body[15] op[0x5b]","timestamp":"2017-02-06T09:21:18-08:00","_body":"0e500082645a00002a000000002a5a","carb_input":14,"bg_target_high":90,"sensitivity":100,"carb_ratio":13,"food_estimate":1.05,"unabsorbed_insulin_total":0,"correction_estimate":0,"bg_target_low":90,"_head":"5b00","bolus_estimate":1.05,"_date":"1295090611"},"timestamp":"2017-02-06T09:21:18-08:00","created_at":"2017-02-06T09:21:18-08:00","eventType":"Carb Correction","notes":"Food estimate 1.05\nCorrection estimate 0\nBolus estimate 1.05\nTarget low 90\nTarget high 90\nHypothetical glucose delta 0","medtronic":"mm://openaps/mm-format-ns-treatments/Carb Correction","enteredBy":"openaps://medtronic/723","insulin":null},{"_id":"5898b113bd4bf2dc76c9dfb2","duration":30,"raw_duration":{"_type":"TempBasalDuration","_description":"TempBasalDuration 2017-02-06T09:18:38 head[2], body[0] op[0x16]","timestamp":"2017-02-06T09:18:38-08:00","_body":"","_head":"1601","duration (min)":30,"_date":"2692094611"},"timestamp":"2017-02-06T09:18:38-08:00","absolute":1,"rate":1,"raw_rate":{"_type":"TempBasal","temp":"absolute","_description":"TempBasal 2017-02-06T09:18:38 head[2], body[1] op[0x33]","timestamp":"2017-02-06T09:18:38-08:00","_body":"00","_head":"3328","rate":1,"_date":"2692094611"},"eventType":"Temp Basal","medtronic":"mm://openaps/mm-format-ns-treatments/Temp Basal","created_at":"2017-02-06T09:18:38-08:00","enteredBy":"openaps://medtronic/723","carbs":null,"insulin":null},
```

**Comment by ceben80** [comment] 2017-02-06 20:14
I confirm this issue with my 522 pump

**Comment by Kdisimone** [comment] 2017-02-06 20:17
Sent the treatments link to you @scottleibrand.  Happy to send to you @cjo20 too, if you want?

**Comment by Kdisimone** [comment] 2017-02-06 20:19
this would appear to be the problem...but what is causing that?

![118__4_](https://cloud.githubusercontent.com/assets/12402160/22664655/7881f4ee-ec66-11e6-8c26-9ef1a02af7a3.jpg)

**Comment by scottleibrand** [comment] 2017-02-06 20:27
Here is a more readable version of those two records:
```
[
  {
    "enteredBy": "openaps://medtronic/723",
    "medtronic": "mm://openaps/mm-format-ns-treatments/Meal Bolus",
    "notes": "Normal bolus with wizard.\nProgrammed bolus 1.05\nDelivered bolus 1.05\nPercent delivered:  100%\nFood estimate 1.05\nCorrection estimate 0\nBolus estimate 1.05\nTarget low 90\nTarget high 90\nHypothetical glucose delta -105",
    "insulin": 1.05,
    "eventType": "Meal Bolus",
    "_id": "5898b2aebd4bf2dc76c9dfbb",
    "duration": 0,
    "bolus": {
      "_date": "0496490611",
      "type": "normal",
      "_head": "01002a002a001800",
      "unabsorbed": 0.6,
      "_type": "Bolus",
      "_description": "Bolus 2017-02-06T09:22:04 head[8], body[0] op[0x01]",
      "timestamp": "2017-02-06T09:22:04-08:00",
      "_body": "",
      "appended": [
        {
          "_date": "",
          "data": [
            {
              "age": 93,
              "amount": 0.4
            },
            {
              "age": 103,
              "amount": 0.15
            },
            {
              "age": 123,
              "amount": 0.55
            },
            {
              "age": 433,
              "amount": 0.5
            },
            {
              "age": 473,
              "amount": 0.55
            }
          ],
          "_head": "5c11105d04066704167b0414b11416d914",
          "_body": "",
          "_description": "UnabsorbedInsulinBolus unknown head[17], body[0] op[0x5c]",
          "_type": "UnabsorbedInsulinBolus"
        }
      ],
      "programmed": 1.05,
      "duration": 0,
      "amount": 1.05
    },
    "timestamp": "2017-02-06T09:22:03-08:00",
    "created_at": "2017-02-06T09:22:03-08:00",
    "carbs": 14,
    "ratio": "13",
    "wizard": {
      "_date": "0396090611",
      "sensitivity": 100,
      "bg_target_high": 90,
      "appended": [
        {
          "_date": "",
          "data": [
            {
              "age": 92,
              "amount": 0.4
            },
            {
              "age": 102,
              "amount": 0.15
            },
            {
              "age": 122,
              "amount": 0.55
            },
            {
              "age": 432,
              "amount": 0.5
            },
            {
              "age": 472,
              "amount": 0.55
            }
          ],
          "_head": "5c11105c04066604167a0414b01416d814",
          "_body": "",
          "_description": "UnabsorbedInsulinBolus unknown head[17], body[0] op[0x5c]",
          "_type": "UnabsorbedInsulinBolus"
        }
      ],
      "_body": "0e500082645a00002a000000002a5a",
      "timestamp": "2017-02-06T09:22:03-08:00",
      "_description": "BolusWizard 2017-02-06T09:22:03 head[2], body[15] op[0x5b]",
      "bg": 0,
      "_type": "BolusWizard",
      "carb_input": 14,
      "carb_ratio": 13,
      "food_estimate": 1.05,
      "unabsorbed_insulin_total": 0,
      "correction_estimate": 0,
      "bg_target_low": 90,
      "_head": "5b00",
      "bolus_estimate": 1.05
    }
  },
  {
    "insulin": null,
    "enteredBy": "openaps://medtronic/723",
    "medtronic": "mm://openaps/mm-format-ns-treatments/Carb Correction",
    "_id": "5898b2aebd4bf2dc76c9dfbc",
    "carbs": 14,
    "ratio": "13",
    "wizard": {
      "_date": "1295090611",
      "bolus_estimate": 1.05,
      "_head": "5b00",
      "bg_target_low": 90,
      "correction_estimate": 0,
      "unabsorbed_insulin_total": 0,
      "food_estimate": 1.05,
      "carb_ratio": 13,
      "_type": "BolusWizard",
      "bg": 0,
      "_description": "BolusWizard 2017-02-06T09:21:18 head[2], body[15] op[0x5b]",
      "timestamp": "2017-02-06T09:21:18-08:00",
      "_body": "0e500082645a00002a000000002a5a",
      "carb_input": 14,
      "bg_target_high": 90,
      "sensitivity": 100
    },
    "timestamp": "2017-02-06T09:21:18-08:00",
    "created_at": "2017-02-06T09:21:18-08:00",
    "eventType": "Carb Correction",
    "notes": "Food estimate 1.05\nCorrection estimate 0\nBolus estimate 1.05\nTarget low 90\nTarget high 90\nHypothetical glucose delta 0"
  }
]
```

**Comment by Kdisimone** [comment] 2017-02-06 20:27
@cjo20 are you thinking that's what a "back out" would look like in treatments log?  @ceben80 can you go back to your treatment logs and look?

**Comment by Kdisimone** [comment] 2017-02-06 20:28
What the heck is a carb correction coming from? ;)

**Comment by Kdisimone** [comment] 2017-02-06 20:29
Shall I try deleting from NS and see if this helps OpenAPS?

**Comment by scottleibrand** [comment] 2017-02-06 20:31
Before deleting, let's look at the pumphistory.json and see if it shows up twice there, or if it's getting the second one from NS...

**Comment by Kdisimone** [comment] 2017-02-06 20:32
They should be able to do that when he's picked up from school

**Comment by cjo20** [comment] 2017-02-06 20:36
I think the fact that both are from "openaps://medtronic/723" suggests that it's originating from the pump. I have a vague recollection of something about mmhistorytools combining dual entries of carbs in some cases. I think that the same functionality was added to oref0 a couple of releases ago?

This is a pure speculation without having looked at code yet: It's possible that 723 pumps generate a "Carb Correction" entry when the bolus wizard is started, and the "Meal Bolus" when the bolus is given. If the event-combining code looks for two events in the same minute then whether they get removed or not would depend on whether both events happened in the same minute or not.

**Comment by Kdisimone** [comment] 2017-02-06 20:37
The next bolus and carb entry were done by same school nurse and no double entry happened.  Perhaps those were same minute reading for that entry in pump.  I'll make a note about that time too.

**Comment by Kdisimone** [comment] 2017-02-06 20:41
But, I also think this is happening on 722 pumps.  Have another rig/pump/openaps user on 722 that I've seen this not self-resolve on.

**Comment by cjo20** [comment] 2017-02-06 20:46
Having looked at the code, I don't think the de-duplication stuff was actually merged, hence deleting my comment.

**Comment by scottleibrand** [comment] 2017-02-06 20:48
Perhaps someone would like to test https://github.com/openaps/oref0/pull/375 and see if it fixes this?

**Comment by Kdisimone** [comment] 2017-02-06 20:51
I can test that...might take a couple days to see if the negative can be proven, but happy to try.

**Comment by cjo20** [comment] 2017-02-06 20:53
It's worth trying, but I don't think it will fix it. The de-duplication checks for two events with the same carb total with the same timestamp. The two entries here are 45 seconds apart.

https://github.com/openaps/oref0/pull/375/files#diff-060f20ba122b5ef0476eec300d40eeacR55

**Comment by sulkaharo** [comment] 2017-02-07 01:13
Afaik the earlier OpenAPS behavior was to always read these as two separate events but only consider the carbs from one of them. The current pump read logic has an issue where the pump can be read during the time the bolus is being administered, so there's a time slot between user having entered the carbs and not having yet confirmed the bolus that'll create a Wizard event with carbs but no bolus and another where during the bolus the pump record will show the carbs and the part of the bolus that's been administered so far but not the entire amount (to ensure the record contains up to date information on bolus given even if the power is cut in the middle of the bolus).

IMO entering carb events without bolusing using the wizard should not be a supported feature and we should change the logic to not consider the carb event without the bolus event (do not sync to Nightscout / do not add to COB). Additionally the pump history read for the ongoing bolus should not be supported; I recall Scott had a reason for wanting to read history even if we detect a bolus is ongoing but can't remember what the rationale was. (There's separate event logic in some pump models to enter log entries, which could be used for additional carbs in addition to NS logging?)

I have a Node based tool I've used as a replacement for the shell script based pump log rewriter the default loop uses, which has logic for merging / detecting the carb event without bolus; I can check how to apply this to reading the log into COB and we could replace parts of the current NS sync with a node based one with more logic on what gets synced.

(Also reminds me, decocare doesn't correctly label all the events with a BG value with the correct BG units on mmol pumps - anyone with python skills wanna help?)

**Comment by scottleibrand** [comment] 2017-02-07 01:27
I agree we should unsupport carb-only bolus wizard entries, and ignore carbs entered without at least a 0.1U bolus.

Only reason I can remember for wanting to read pumphistory while bolusing is for extended boluses.

In the SMB branch I've re-done the pump-loop aliases as a single shell script (based on some stuff @cjo20 did): that could have a bolusing check before pulling pumphistory, if that's important.  We already can't enact temps if bolusing, so it only matters for uploading to NS I think.

**Comment by moomoobloo** [comment] 2017-02-07 02:04
> I agree we should unsupport carb-only bolus wizard entries, and ignore carbs entered without at least a 0.1U bolus.

AFAIK, the bolus wizard is the only way to enter carbs in offline mode. If we require insulin to be delivered, it would be impossible to enter carb corrections or any other carbs that don't correspond to a bolus when offline. If that's the case, I think it should be supported. Is there a way to distinguish between failed/cancelled bolus wizard records vs ones that are intentionally entered without carbs?

BTW, a while ago I looked into a case where carbs were being logged after cancelling the bolus wizard. To confirm the expected behavior, I uploaded my pump data to carelink.minimed.com and the carbs were in fact being logged there as well. So at least according to Medtronic, the current behavior is "correct". Not sure if we care about parity with Medtronic (and potentially Tidepool), but it's something to consider.

**Comment by scottleibrand** [comment] 2017-02-07 02:07
I don't know of any way to tell the difference between canceled bolus wizard entries and entries where zero bolus was selected.  Given that, I would prefer to force users to enter a 0.1U bolus with their carbs if they want them considered by oref0, so there is no ambiguity or chance of misinterpretation.

**Comment by cjo20** [comment] 2017-02-07 02:11
If you're going to force a bolus to enter carbs, please can the check be >0 insulin (rather than >= 0.1)

**Comment by scottleibrand** [comment] 2017-02-07 02:17
Ok, yeah.  For 523s you can do 0.025U instead of 0.1U like you have to do on 522s, so that would be better.

**Comment by moomoobloo** [comment] 2017-02-07 02:22
523 still requires bolus to be >= 0.1 (but basal rate can be as low as .025/hr).

@scottleibrand If you're going to change the behavior to ignore bw entries without insulin, can you make it an optional feature? It's not feasible for small children to get 0.1U along with a carb correction in order for carb logging to work offline.

**Comment by cjo20** [comment] 2017-02-07 02:23
@moomoobloo 554 allows 0.025u boluses.

**Comment by scottleibrand** [comment] 2017-02-07 02:29
I just tested and was able to deliver a 0.025U bolus on a non-loopable 523 with 2.5B.  I presume loopable 523s are the same, but maybe not.

**Comment by JELCRAWFORD** [comment] 2017-02-07 04:55
Hi all - we have a 754 pump and have had issues with the COB report.  The APS will often report more carb than was actually given.  The NS number when we hover over the pill looks as we would expect.  We have not determined cause.  It is NOT double entries - we no longer use careportal for any entries that involve insulin (basically any entry that goes through the pump).  We do use careportal for carb corrections (w/o insulin, of course).  Instead our DS enters a note at school when he eats so we have info we need - in the note he indicates insulin given, any corrections, and carb total etc.  We have him do this in the event that the APS isn't working or pump info isn't populated for some reason so we will still have a notion about what he's got for IOB and COB.  This elimiated the double entry issue but did not stop the weird carb numbers that appear.  The 'extra; COB will sometimes resolve itself, but often can be a long time (i.e. hours).

**Comment by JELCRAWFORD** [comment] 2017-02-07 05:02
One thought - we were just reviewing our COB issues - we can't recall ever seeing this issue except in the evenings.  DS also almost always has a very big spike in the evenings - shortly after he falls asleep, which seems to correspond to the spike.  Admittedly, as we've always had to be 'on' because of the spike, we are usually both watching and it is possible we haven't noticed the same COB issues during the day (though usually at least one of us is watching, most of the day)therefore we may have the impression it doesn't happen any other time and that could be erroneous.... 

We had theorized that  APS, when seeing the large rise is assuming COB that is not accounted for and then was estimating COB instead of using the actual COB, which is why we end up with greater COB than he has actually eaten or sometimes end up with a sudden change to a bigger number of COB hours after he has been asleep.  Short of that, we have not had a great understanding.  Because of this, though, we tend to watch more carefully in the evenings in case a large COB were to cause the APS to not respond properly to a low and then we intervene if we need to.  I'm sure several of you can debunk our working theory :)

**Comment by Kdisimone** [comment] 2017-02-07 05:06
Our 723 goes 0.025 for boluses.

**Comment by Kdisimone** [comment] 2017-02-07 05:06
and thank you all so much for looking into this today!  much appreciated!

**Comment by JELCRAWFORD** [comment] 2017-02-07 05:29
It seems our 754 only does 0.1 - am surprised that the 754 and 554 aren't the same in this regard...

**Comment by scottleibrand** [comment] 2017-02-07 05:32
@JELCRAWFORD which "COB report" are you talking about?  Do you have the Nightscout COB pill enabled?

**Comment by JELCRAWFORD** [comment] 2017-02-07 05:33
yes, both NS and APS so that when we hover we can see NS COB.  Display defaults to APS number

**Comment by scottleibrand** [comment] 2017-02-07 05:35
And are you seeing it switch back and forth sometimes, or is it always the OpenAPS COB that you're seeing unexpected numbers with?  If it's the latter, you might want to check your treatments collection to see if you're seeing double carb entries, or if it might be something else.  @Kdisimone how did you get that screenshot of the carb entries?  Is that the mlab interface?

**Comment by JELCRAWFORD** [comment] 2017-02-07 05:41
Prior to this moment, I'd have said it is always OpenAPS, however, as it stands, we are showing 3 carbs in OpenAPS COB pill from a 6:15 supper of 60 carbs, but 44 carbs according to NS.  In this instance, I'd be inclined to go with OpenAPS number...  Admittedly, at least the 44 is less than the 60 as we'd expect a decaying number of carbs...

**Comment by scottleibrand** [comment] 2017-02-07 05:45
Can you try disabling the NS COB pill for awhile and just use the OpenAPS pill's COB number?  I don't like the way the NS COB pill switches back and forth between the OpenAPS data and its own calculation.  We might need to do some work on a way to disable that, so it always displays the last OpenAPS COB number, and never displays it own calculation.  That would be a different issue, though.  For this issue, we just need to figure out if you're seeing double COB or something different.

**Comment by JELCRAWFORD** [comment] 2017-02-07 05:47
yup, can do.

**Comment by Kdisimone** [comment] 2017-02-07 05:50
Carb entries screen shot were from NS reports, treatment tab. @scottleibrand

**Comment by scottleibrand** [comment] 2017-02-07 05:53
Thanks.  @JELCRAWFORD can you also check your NS reports, treatment tab the next time you see an issue, and see if there are duplicate treatments there?

**Comment by JELCRAWFORD** [comment] 2017-02-07 06:02
yup.  can do.

**Comment by Kdisimone** [comment] 2017-02-07 06:05
@scottleibrand I had checked it there on previous times I've seen this happen, and there were double entries in there on those times too.

**Comment by scottleibrand** [comment] 2017-02-07 06:07
@Kdisimone Yeah, I think we have a pretty good handle on what's happening in your case, just not why or what to do about it.  Maybe https://github.com/openaps/oref0/pull/375 will prove a decent fix; if not we'll need to look at some other options to filter out carb-only treatments like we discussed earlier, or maybe figure out some way to deduplicate them.

**Comment by Kdisimone** [comment] 2017-02-07 06:07
Here...this one happened to us on Jan 30th.

![108_-17_](https://cloud.githubusercontent.com/assets/12402160/22679661/a5882506-ecb8-11e6-80b7-de0de951b18f.jpg)

**Comment by JELCRAWFORD** [comment] 2017-02-07 07:04
Ok - I hope these come out ok.  First set of images - NS screen shot - Jan 4th.  2nd and 3rd images are of the treatment reports - I think on looking it is somehow summing all of the COB w/o decay over a long period of time....  
![jan 4th cob issues](https://cloud.githubusercontent.com/assets/24684595/22681097/ba41026e-ecc8-11e6-893d-b1cbb9bc65a5.PNG)
![image 1 - jan 4th](https://cloud.githubusercontent.com/assets/24684595/22681124/dd7f86a6-ecc8-11e6-9e2a-be291490f031.png)
![image 2 - jan 4th](https://cloud.githubusercontent.com/assets/24684595/22681127/dfc65476-ecc8-11e6-88bc-9de30299611f.png)

**Comment by JELCRAWFORD** [comment] 2017-02-07 07:05
Sorry, first image was meant to be 2nd set of data.  Please refer to this image below of NS that corresponds with treatment data above.
![jan 4th - cob issues 1](https://cloud.githubusercontent.com/assets/24684595/22681182/1eb1ffbe-ecc9-11e6-807a-224b4c6fef93.PNG)

**Comment by scottleibrand** [comment] 2017-02-07 07:08
I don't see any doubled carb entries there, so looks like your issue is different. Can you open a new issue so we can troubleshoot the COB decay separately?

**Comment by JELCRAWFORD** [comment] 2017-02-07 07:09
NOW 2nd set - Jan 3rd - note the time - 1:12AM  - no way we should have 26 COB (beautiful line though, so that made up for it in some regard!)
![jan 3rd cob issues](https://cloud.githubusercontent.com/assets/24684595/22681205/395c46f8-ecc9-11e6-9bb2-17715442e241.PNG)

![treatments jan 3](https://cloud.githubusercontent.com/assets/24684595/22681260/7a2af422-ecc9-11e6-94e1-55d5ea956020.png)

**Comment by JELCRAWFORD** [comment] 2017-02-07 07:11
maybe.....  I might need help with how to do that from here...

**Comment by hilarykoch** [comment] 2017-02-12 00:20
I'm new to OpenAPS. Got setup last weekend and ran it for maybe 8 hours. Just started again tonight. Each time I bolus through our 522, NS shows COB as doubled. (OpenAPS pill and NS COB pill) I've tried bolusing with a fake BG (in range) and without. It still happens. I've tried using the easy bolus (B button) and through the bolus wizard and it still happens.  Last weekend, it resolved itself within an hour. Tonight, I just deleted the treatment. You can see from the treatment report, both show up at 6:03. I did not back out of a bolus or double enter carbs. 
![img_0759](https://cloud.githubusercontent.com/assets/11912289/22858546/ecc03984-f08e-11e6-8192-34be29b6c7c2.PNG)

**Comment by hilarykoch** [comment] 2017-02-12 00:40
Adding this pic. Can't seem to get a pic showing when it was entered at 6:03, so the doubled carbs showed 80, but you can see this one has 76 - still more than the 40 it should have been.
<img width="1169" alt="screen shot 2017-02-11 at 7 36 54 pm" src="https://cloud.githubusercontent.com/assets/11912289/22858667/a9e4f75a-f091-11e6-8740-e9d1593b8ef2.png">

**Comment by hilarykoch** [comment] 2017-02-12 01:43
I was able to determine the double carb entries appear in OpenAPS COB pill and NS COB pill if bolusing through pump, but Loop app is enabled on (either in open or closed Loop mode). When bolusing through Loop app (again either in closed or open Loop mode), double carb entries do not appear in NS COB or OpenAPS COB pills. The solution seems to be either to close Loop app entirely and bolus through pump or bolus through Loop app.

**Comment by danamlewis** [comment] 2017-02-12 02:45
Sounds like for Loop/OpenAPS dual rig users, it was Loop uploading to NS causing the double entries. I wrote up info in the docs (https://github.com/openaps/docs/pull/650) about the suggestion to turn off loop's ability to upload to NS to resolve this if people want to use Loop to bolus but OpenAPS for looping. Additional PRs to that welcome, but will close this issue in next few days and consider it resolved if we don't hear of any other users for which this solution does not resolve.

**Comment by Kdisimone** [comment] 2017-02-13 03:50
My original issue did generate from Loop app use...it was only during OpenAPS use.  @scottleibrand Do you think that #375 will solve it?  I can use that I guess...problem seems to be so intermittent that I'm not sure how long it would take to prove the negative (no more double COBs).

**Comment by tim2000s** [comment] 2017-03-10 19:57
I'm seeing the issue show up again immediately after my rig and pump lost connection then were reconnected. Something in that process is causing a problem.

**Comment by lukasz-kaniowski** [comment] 2017-04-23 17:41
My girlfriend experienced the same issue. She was using bolus wizard and enter 55 carbs but then went back and modified it to 65. Pumphistory shows both entries for some reason. 
She is using Veo 554. 

I've digged into `pumphistory.json` and found this 
``` json
[
  {
    "_type": "BolusWizard",
    "bg": 0,
    "bg_target_high": 6.1,
    "_description": "BolusWizard 2017-04-22T19:49:02 head[2], body[15] op[0x5b]",
    "timestamp": "2017-04-22T19:49:02",
    "_body": "419000501e2c00014400000001443d",
    "_head": "5b00",
    "unabsorbed_insulin_total": 0,
    "correction_estimate": 0,
    "_date": "4231131611",
    "bolus_estimate": 8.1,
    "appended": [
      {
        "_type": "UnabsorbedInsulinBolus",
        "_description": "UnabsorbedInsulinBolus unknown head[11], body[0] op[0x5c]",
        "data": [
          {
            "amount": 1,
            "age": 30
          },
          {
            "amount": 0.5,
            "age": 250
          },
          {
            "amount": 2.7,
            "age": 380
          }
        ],
        "_body": "",
        "_head": "5c0b281ec014fac06c7cd0",
        "_date": ""
      },
      {
        "_body": "",
        "_head": "3108",
        "_type": "Base",
        "_date": "4231131611",
        "_description": "Base (2017, 4, 22, 19, 49, 2) head[2], body[0] op[0x31]"
      }
    ],
    "bg_target_low": 4.4,
    "carb_ratio": 8,
    "food_estimate": 8.1,
    "carb_input": 65,
    "sensitivity": 3
  },
  {
    "_type": "BolusWizard",
    "bg": 0,
    "bg_target_high": 6.1,
    "_description": "BolusWizard 2017-04-22T19:48:28 head[2], body[15] op[0x5b]",
    "timestamp": "2017-04-22T19:48:28",
    "_body": "379000501e2c00011000000001103d",
    "_head": "5b00",
    "unabsorbed_insulin_total": 0,
    "correction_estimate": 0,
    "_date": "5c30131611",
    "bolus_estimate": 6.8,
    "bg_target_low": 4.4,
    "carb_ratio": 8,
    "food_estimate": 6.8,
    "carb_input": 55,
    "sensitivity": 3
  }
]
```

Brief analysis shows that the one that we want to ignore doesn't have `appended` field. I've modified `oref0-meal` code yesterday to check for`appended` field. After 24h it seems that with this small change it is working fine. Anyone knows what `appended` field is used for?

**Comment by scottleibrand** [comment] 2017-04-23 17:46
That field represents the data from the pump, which Nightscout doesn't do anything with. 

You can't edit the immutable records in the pump, so editing in NS just results in duplicating it. On one level, the fix is "don't do that", but we probably also need more comprehensive code to detect and deal with duplicates. Unfortunately, there are many different ways for users to enter boluses and carbs, so there are a lot of different cases to deal with. To date, no one has decided to take on that task, and we all just learn to stick to input methods that don't generate duplicates.

**Comment by lukasz-kaniowski** [comment] 2017-04-23 18:01
In our case we have medtronic cgm so we rely on openaps to upload the data to nightscout. 

The solution in this case would be to ignore bolus wizard entries that doesn't have `appended` field when uploading to NS and when calculating `meal.json`. 
In https://github.com/openaps/oref0/issues/387#issuecomment-277803122 the second entry also doesn't have the `appended` field.

**Comment by danamlewis** [comment] 2017-07-04 02:38
Seems to be resolved through a number of solutions. please reopen or create a new issue if this arises in another setup.

**Closed by danamlewis** 2017-07-04 02:38 UTC
