### ISSUE TITLE
The case of the disappearing carbs (zero temp after bolus wizard)

### ISSUE THREAD

**Issue by LongboatAline** [openaps/oref0#952] opened 2018-03-15 21:36 UTC
Trying to document a conundrum I'm milling over for a while now. Each time I'm bolusing for food, OpenAPS/oref0 goes into panic mode, prognosing outcomes in the deep abbyss of negative bgs, and zero-temping for hours. I think I'm starting to understand to a certain extent what's happening, so today I did a test run for documentation.

- 12:21 eating soon. 
   ```
   Temp refreshed: monitor/temp_basal.json: {"duration":30,"rate":2.85,"temp":"absolute"}
   ```
- 12:30 Used the pump bolos wizard to dose for 40g kh, resulting in 5,7IE. One run of the pump loop hits right while bolusing, the next one picks up a load of IOB, no COB, predicts a horrible outcome, and slams in a zero-temp _fast_.
   ```
   Starting oref0-pump-loop at Thu Mar 15 12:35:02 CET 2018 with 27 second wait_for_silence:
   Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
   Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
   Preflight OK. Profile less than 60m old; Profile valid. Refreshed pumphistoryskipping bolus wizard entry with 40 g carbs and no insulin
    and meal.json
   Checking pump clock: "2018-03-15T12:36:38+01:00" is within 90s of current time: Thu Mar 15 12:36:40 CET 2018
   Temp refreshed
   Autotune exists! Hoorah! You can use microbolus-related features.
   {"carbs":0,"nsCarbs":0,"bwCarbs":0,"journalCarbs":0,"mealCOB":0,"currentDeviation":1.58,"maxDeviation":1.91,"minDeviation":-0.14,"slopeFromMaxDeviation":-0.304,"slopeFromMinDeviation":0.338,"allDeviations":[2,1,2,2,1,0,0],"lastCarbTime":0,"bwFound":false}
   {"iob":6.062,"activity":0.006,"basaliob":0.426,"bolusiob":5.636,"netbasalinsulin":1.5,"bolusinsulin":5.65,"time":"2018-03-15T11:36:47.000Z","iobWithZeroTemp":{"iob":6.062,"activity":0.006,"basaliob":0.426,"bolusiob":5.636,"netbasalinsulin":1.5,"bolusinsulin":5.65,"time":"2018-03-15T11:36:47.000Z"},"lastBolusTime":1521113483000,"lastTemp":{"rate":2.85,"timestamp":"2018-03-15T12:27:33+01:00","started_at":"2018-03-15T11:27:33.000Z","date":1521113253000,"duration":10.31}}
   {"delta":0,"glucose":99,"noise":null,"short_avgdelta":0.94,"long_avgdelta":1.59,"date":1521113443398}
   Autosens ratio: 1; Basal unchanged: 0.75; ISF unchanged: 35; CR: 7.072
   currenttemp: { duration: 22, rate: 2.85, temp: 'absolute' } lastTempAge: 9 m tempModulus: 1 m
   SMB disabled (no enableSMB preferences active)
   Carb Impact: 1.1 mg/dL per 5m; CI Duration: 0 hours; remaining CI (~2h peak): 0 mg/dL per 5m
   UAM Impact: 1.1 mg/dL per 5m; UAM Duration: 0.3 hours
   minPredBG: -47 minIOBPredBG: 39 minZTGuardBG: -47 minUAMPredBG: 39 avgPredBG: -47 COB: 0 / 0
   BG projected to remain above 80 for 40 minutes
   BG projected to remain above 60 for 60 minutes
   naive_eventualBG: -113 bgUndershoot: 173 zeroTempDuration: 60 zeroTempEffect: 26 carbsReq: 30
   2018-03-15T11:36:55.631Z
   Checking deliverAt: 2018-03-15T11:36:55.631Z is within 1m of current time: Thu Mar 15 12:36:55 CET 2018
   and that smb-suggested.json is less than 1m old
   enact/smb-suggested.json: {"temp":"absolute","bg":99,"tick":"+0","eventualBG":39,"insulinReq":0,"reservoir":"34.075","deliverAt":"2018-03-15T11:36:55.631Z","sensitivityRatio":1,"predBGs":{"IOB":[99,99,
   98,96,94,90,86,82,77,72,67,61,55,49,43,
   39],"ZT":[99,98,96,93,90,86,82,77,73
   ,67,62,57,51,46,40,39,39,39,39,39,39,39
   ,39,39,39,39,39,39,39,39,39,39,39,39,39
   ,39,39,39,39,39,39,39,39,39,39,39,39,39
   ],"UAM":[99,99,97,95,92,88,83,78,73,68
   ,62,57,51,45,39]},"COB":0,"IOB":6.062
   ,"reason":"COB: 0, Dev: 6, BGI: -1, ISF: 35, CR: 7.07, Target: 80, minPredBG -47, minGuardBG -97, IOBpredBG 39, UAMpredBG 39; minGuardBG -97<60"
   ,"duration":120,"rate":0}
   Temp refreshed: monitor/temp_basal.json: {"duration":21,"rate":2.85,"temp":"absolute
   "}
   enact/smb-enacted.json: "Rate: 0 Duration: 120"
   Temp refreshed: monitor/temp_basal.json: {"duration":120,"rate":0,"temp":"absolute"
   }
   No bolus needed. Settings less than 15 minutes old. Edison on battery: 90%. Pumphistory-24 < 30m old
   Pump profile refreshed; Settings refreshed; Refreshed pumphistoryskipping bolus wizard entry with 40 g carbs and no insulin
    and meal.json
   IOB: null
   Your instance of oref0 [0.6.1-dev, dev] is up-to-date.
   Completed oref0-pump-loop at Thu Mar 15 12:38:32 CET 2018
   ```
- after the fact, in the last lines of the pump loop quoted above, it actually did detect the Carbs: `skipping bolus wizard entry with 40 g carbs and no insulin`, so here's the Nightscout view from that time and the following pump-loop:
![1240-cob](https://user-images.githubusercontent.com/35570803/37492182-b44effae-28a0-11e8-9147-018d14153615.png)

   ```
   Starting oref0-pump-loop at Thu Mar 15 12:39:02 CET 2018 with 9 second wait_for_silence:
   Retrying without waiting for new BG
   Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
   Preflight OK. Profile less than 60m old; Profile valid. Refreshed pumphistory and meal.json
   Checking pump clock: "2018-03-15T12:40:21+01:00" is within 90s of current time: Thu Mar 15 12:40:24 CET 2018
   Temp refreshed
   Autotune exists! Hoorah! You can use microbolus-related features.
   {"carbs":40,"nsCarbs":40,"bwCarbs":0,"journalCarbs":0,"mealCOB":1,"currentDeviation":3.39,"maxDeviation":1.91,"minDeviation":-0.14,"slopeFromMaxDeviation":0,"slopeFromMinDeviation":0.608,"allDeviations":[3,1,2,2,1,0,0],"lastCarbTime":1521113483000,"bwFound":false}
   {"iob":5.98,"activity":0.01,"basaliob":0.373,"bolusiob":5.607,"netbasalinsulin":1.5,"bolusinsulin":5.65,"time":"2018-03-15T11:40:31.000Z","iobWithZeroTemp":{"iob":5.98,"activity":0.01,"basaliob":0.373,"bolusiob":5.607,"netbasalinsulin":1.5,"bolusinsulin":5.65,"time":"2018-03-15T11:40:31.000Z"},"lastBolusTime":1521113483000,"lastTemp":{"rate":0,"timestamp":"2018-03-15T12:37:15+01:00","started_at":"2018-03-15T11:37:15.000Z","date":1521113835000,"duration":4.35}}
   {"delta":3,"glucose":102,"noise":null,"short_avgdelta":1.94,"long_avgdelta":1.96,"date":1521113743242}
   Autosens ratio: 1; Basal unchanged: 0.75; ISF unchanged: 35; CR: 7.072
   currenttemp: { duration: 118, rate: 0, temp: 'absolute' } lastTempAge: 3 m tempModulus: 1 m
   SMB disabled (no enableSMB preferences active)
   Last carbs 9 minutes ago; remainingCATime: 3.2 hours; 98% carbs absorbed
   Carb Impact: 3.7 mg/dL per 5m; CI Duration: 0.2 hours; remaining CI (~2h peak): 0 mg/dL per 5m
   predCIs (mg/dL/5m): 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   remainingCIs:       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   UAM Impact: 3.7 mg/dL per 5m; UAM Duration: 1.6 hours
   minPredBG: -43 minIOBPredBG: 39 minZTGuardBG: -43 minCOBPredBG: 39 minUAMPredBG: 39 avgPredBG: -43 COB: 1 / 40
   BG projected to remain above 80 for 40 minutes
   BG projected to remain above 60 for 55 minutes
   naive_eventualBG: -107 bgUndershoot: 167 zeroTempDuration: 55 zeroTempEffect: 24 carbsReq: 29
   2018-03-15T11:40:39.987Z
   Checking deliverAt: 2018-03-15T11:40:39.987Z is within 1m of current time: Thu Mar 15 12:40:40 CET 2018
   and that smb-suggested.json is less than 1m old
   enact/smb-suggested.json: {"temp":"absolute","bg":102,"tick":"+3","
   eventualBG":39,"insulinReq":0,"reservoir":"34.025","deliverAt":"2018-03-15T11:40:39.987Z","sensitivityRatio":1,"predBGs":{"IOB":[102,104
   ,104,104,103,100,98,94,90,85,80,75,69,63,57
   ,51,45,39],"ZT":[102,100,98,95,91,87,
   82,77,72,67,62,56,51,45,40,39,39,39,39,
   39,39,39,39,39,39,39,39,39,39,39,39,39,
   39,39,39,39,39,39,39,39,39,39,39,39,39,
   39,39,39],"COB":[102,103,101,98,94,90,85
   ,80,75,69,64,58,52,46,40,39],"UAM":[102
   ,104,105,104,104,102,100,97,94,90,86,82,77
   ,72,67,62,56,50,45,39]},"COB":1,"IOB"
   :5.98,"reason":"COB: 1, Dev: 22, BGI: -2, ISF: 35, CR: 7.07, Target: 80, minPredBG -43, minGuardBG -64, IOBpredBG 39, COBpredBG 
   39, UAMpredBG 39; minGuardBG -64<60 118m left and 0 ~ req 0U/hr: no temp required"}
   No smb_enact needed. Temp refreshed: monitor/temp_basal.json: {"duration":118,"rate":0,"temp":"absolute"}
   No bolus needed. Settings less than 15 minutes old. Edison on battery: 90%. pumphistory-24h refreshed
   Pump profile refreshed; Settings refreshed; Refreshed pumphistory and meal.json
   IOB: 5.92
   Your instance of oref0 [0.6.1-dev, dev] is up-to-date.
   Completed oref0-pump-loop at Thu Mar 15 12:42:18 CET 2018
   ```

![1241-openaps-0tmpstarted](https://user-images.githubusercontent.com/35570803/37492216-da92c4ac-28a0-11e8-8b39-c150f6d5d1d1.png)

![1242-openaps-cob1](https://user-images.githubusercontent.com/35570803/37492229-e4660020-28a0-11e8-988a-9b3ad9fb7b7a.png)

**Comment by LongboatAline** [comment] 2018-03-15 21:38
(This is getting lengthy, and probably more information needed, so I'm saving for the moment)

**Comment by LongboatAline** [comment] 2018-03-15 23:44
`settings/profile.json`, formatted and stripped by the BR.
```js
{
    "max_iob": 9, 
    "max_daily_safety_multiplier": 5, 
    "current_basal_safety_multiplier": 6, 
    "autosens_max": 2.2, 
    "autosens_min": 0.7, 
    "rewind_resets_autosens": true, 
    "high_temptarget_raises_sensitivity": false, 
    "low_temptarget_lowers_sensitivity": false, 
    "sensitivity_raises_target": true, 
    "resistance_lowers_target": false, 
    "adv_target_adjustments": false, 
    "exercise_mode": false, 
    "half_basal_exercise_target": 160, 
    "maxCOB": 120, 
    "wide_bg_target_range": false, 
    "unsuspend_if_no_temp": false, 
    "bolussnooze_dia_divisor": 2, 
    "min_5m_carbimpact": 8, 
    "autotune_isf_adjustmentFraction": 1, 
    "remainingCarbsFraction": 1, 
    "remainingCarbsCap": 90, 
    "enableUAM": true, 
    "A52_risk_enable": false, 
    "enableSMB_with_COB": false, 
    "enableSMB_with_temptarget": false, 
    "enableSMB_always": false, 
    "enableSMB_after_carbs": false, 
    "allowSMB_with_high_temptarget": false, 
    "maxSMBBasalMinutes": 30, 
    "curve": "rapid-acting", 
    "useCustomPeakTime": false, 
    "insulinPeakTime": 75, 
    "carbsReqThreshold": 1, 
    "offline_hotspot": false, 
    "noisyCGMTargetMultiplier": 1.3, 
    "suspend_zeros_iob": true, 
    "dia": 6, 
    "model": "754", 
    "current_basal": 0.755, 
    "basalprofile": [
        {
            "i": 0, 
            "minutes": 0, 
            "rate": 0.587, 
            "start": "00:00:00"
        }
    ], 
    "max_daily_basal": 0.845, 
    "max_basal": 4, 
    "out_units": "mg/dL", 
    "min_bg": 90, 
    "max_bg": 90, 
    "bg_targets": {
        "units": "mg/dL", 
        "user_preferred_units": "mg/dL", 
        "targets": [
            {
                "i": 0, 
                "high": 90, 
                "start": "00:00:00", 
                "low": 90, 
                "offset": 0, 
                "x": 0, 
                "max_bg": 90, 
                "min_bg": 90
            }
        ], 
        "first": 1
    }, 
    "sens": 35, 
    "isfProfile": {
        "first": 1, 
        "sensitivities": [
            {
                "endOffset": 360, 
                "i": 0, 
                "offset": 0, 
                "sensitivity": 66.523, 
                "start": "00:00:00", 
                "x": 0
            }, 
            {
                "i": 12, 
                "offset": 360, 
                "sensitivity": 28, 
                "start": "06:00:00", 
                "x": 1
            }, 
            {
                "i": 18, 
                "offset": 540, 
                "sensitivity": 30, 
                "start": "09:00:00", 
                "x": 2
            }, 
            {
                "i": 22, 
                "offset": 660, 
                "sensitivity": 35, 
                "start": "11:00:00", 
                "x": 3, 
                "endOffset": 1440
            }
        ], 
        "units": "mg/dL", 
        "user_preferred_units": "mg/dL"
    }, 
    "carb_ratio": 7.072, 
    "carb_ratios": {
        "units": "grams", 
        "first": 1, 
        "schedule": [
            {
                "i": 0, 
                "start": "00:00:00", 
                "offset": 0, 
                "ratio": 7.072, 
                "x": 0
            }
        ]
    }
}
```

**Comment by scottleibrand** [comment] 2018-03-15 23:45
How are you entering the disappearing carbs? Bolus Wizard? With or without a bolus? Can you paste the corresponding record from the pumphistory?

**Comment by LongboatAline** [comment] 2018-03-16 00:07
I think I found it, in `settings/pumphistory-24h.json`
```
  {
    _type: BolusWizard, 
    bg: 9.9, 
    bg_target_high: 9.0, 
    _description: BolusWizard 2018-03-15T12:31:23 head[2], body[15] op[0x5b], 
    timestamp: 2018-03-15T12:31:23, 
    _body: 28500048505a0400de00000000e25a, 
    _head: 5b63,   
    unabsorbed_insulin_total: 0.0, 
    correction_estimate: 0.1, 
    _date: 17df0c6f12, 
    bolus_estimate: 5.65, 
    bg_target_low: 9.0, 
    carb_ratio: 7.2, 
    food_estimate: 5.55, 
    carb_input: 40, 
    sensitivity: 8.0
  },
```

**Comment by alimhassam** [comment] 2018-03-16 00:12
@LongboatAline 
Could you post the corresponding bolus record as well, should be right before or right after?

**Comment by alimhassam** [comment] 2018-03-16 00:15
also let us know if it was before or after, if you do find it.

**Comment by LongboatAline** [comment] 2018-03-16 00:17
I've updated the entry with the other records from the file in the order they're appearing. older entries seem to sink to the bottom of the file, so the bolus wizard comes first, then the bolus, then the zerotemp

**Comment by LongboatAline** [comment] 2018-03-16 00:32
From the merged pumphistory (on fileserver)
```
  {
    "_type": "TempBasal",
    "temp": "absolute",
    "_description": "TempBasal 2018-03-15T12:37:15 head[2], body[1] op[0x33]",
    "timestamp": "2018-03-15T12:37:15+01:00",
    "_body": "00",
    "_head": "3300",
    "rate": 0,
    "_date": "0fe50c4f12"
  },
  {
    "_type": "TempBasalDuration",
    "_description": "TempBasalDuration 2018-03-15T12:37:15 head[2], body[0] op[0x16]",
    "timestamp": "2018-03-15T12:37:15+01:00",
    "_body": "",
    "_head": "1604",
    "duration (min)": 120,
    "_date": "0fe50c4f12"
  },
  {
    "_type": "BolusWizard",
    "bg": 9.9,
    "_description": "BolusWizard 2018-03-15T12:31:23 head[2], body[15] op[0x5b]",
    "timestamp": "2018-03-15T12:31:23+01:00",
    "_body": "28500048505a0400de00000000e25a",
    "carb_input": 40,
    "bg_target_high": 9,
    "sensitivity": 8,
    "carb_ratio": 7.2,
    "food_estimate": 5.55,
    "unabsorbed_insulin_total": 0,
    "correction_estimate": 0.1,
    "bg_target_low": 9,
    "_head": "5b63",
    "bolus_estimate": 5.65,
    "_date": "17df0c6f12"
  },
  {
    "programmed": 5.65,
    "_type": "Bolus",
    "_description": "Bolus 2018-03-15T12:31:23 head[8], body[0] op[0x01]",
    "timestamp": "2018-03-15T12:31:23+01:00",
    "_body": "",
    "_head": "0100e200e2000000",
    "amount": 5.65,
    "unabsorbed": 0,
    "duration": 0,
    "type": "normal",
    "_date": "17df4c6f12"
  },
```

**Comment by alimhassam** [comment] 2018-03-16 00:54
to be confirmed, but as per comment here, i *think* this could be due to the fact that version of jq might not have stable sorting:
https://gitter.im/openaps/oref0?at=5aab1265f3f6d24c687d6079

**Comment by JELCRAWFORD** [comment] 2018-03-16 05:57
@alimhassam @LongboatAline  @scottleibrand - we were looking at this tonight after the above post as well.  We have been observing the 'skipping' error and could not figure it out and also have immediate and long zero temps after meals with predictions suggesting that BG will drop rapidly and severely, along with frustrating highs that are often requiring manual correction.  These things are happening very often, and though we did not associate it with BW entries before, on review we believe this is also the case for us.  

Our son uses BW entries at school and with caregivers, so his usage of BW is more often than not.   If this is related to BW use and does not happen with other entry methods (making the solution to NOT use BW), this could be a bigger complication for those who have less savvy caregivers supervising their pwd.  Of course, calculating necessary insulin is not as easy for a child or dependant pwd as it would be for a pwd that is independent.  fwiw - jq version is 1.4.   We can post logs if it is helpful though I think the examples will be similar to @LongboatAline .

**Comment by alimhassam** [comment] 2018-03-16 16:45
@JELCRAWFORD Didn't update it here, but after some investigation yesterday,  changing jq version didn't seem to have helped.
The issue is fixed in next major version of oref0, but it's not something that can easily be cherry-picked to dev.

**Comment by JELCRAWFORD** [comment] 2018-03-16 17:51
@scottleibrand  - is there a timeline on release of next version?

Also, we realize the original iterations did not have use of  BW as a primary method of data entry via pump, however it is a feature that I think many people with dependent PWD's continue to use for simplicity with caregivers, particularly and also to assist younger pwd's in independent mgmt.  It seems likely this bug then impacts that group, perhaps to a proportionally higher degree - should we be alerting the community so that people can watch for this and address it as best they can given the circumstances if they are experiencing it?

**Comment by jenm999** [comment] 2018-03-16 19:56
This is alarming. I have looked at the last four boluses in nightscout and the COB is always accurately (as far as I can guess estimating on the math) displayed in the OpenAPS pill. How would I verify that our bolus method is not creating this problem? Our son boluses himself using the BW (in fact, easy bolus is disabled because I feel it's too easy to inadvertently initiate a bolus) - he skips BG and enters carbs only. Since our ratios are 1:8 and 1:15 this is not math that he's going to be doing on the fly.

**Comment by JELCRAWFORD** [comment] 2018-03-17 16:04
@jenm999 - the openaps pill does seem to be correct, however when we look in the loop log we find the message like this "skipping bolus wizard entry with 36 g carbs and no insulin". It seems maybe the carbs are acknowledged but then disregarded because the system doesn't think there is insulin attached?  So perhaps check your loop log on a meal he uses BW and see if that message is there.  When we don't use BW, we do not see these messages.  It would be unusual for DS to have carbs (particularly large amounts) without a bolus - this message has puzzled us for some time.  @LongboatAline 's issue is what brought it to our attention as a bigger potential problem.  It is easy enough to not use BW for DS at home and we can try to make one of us available to support lunchtime bolus at school, but it is not ideal and when he's with caregivers I think this will be actually quite problematic to have to operate in this way - his ratio's are updated yesterday to 8.5:1 for breakfast and 9.5:1 for everything else - I don't think he can reliably, and error free, do the math for this.... maybe I underestimate him.  I don't know if others have recognized this problem from other spots in their log...  I believe there maybe has been some other chatter in some of the other gitter channels about this too.

**Comment by jenm999** [comment] 2018-03-17 16:11
@JELCRAWFORD  Thank you for the explanation. My son is 10 and quite capable of the math, but will he do it when he's flying solo and eager to get back to his friends? He will guess. And if he enters insulin without the corresponding carbs, which I'm guessing you'd need to do via IFTTT or Workflow or the caregiver portal, it will create even more of a mess. The whole reason we are doing OpenAPS vs Loop is that he always has the same task and never has to troubleshoot: bolus from pump, full stop. 

He's not with me now so I don't believe I can see the logs on the rig (unless they are passed along to papertrail?) but I will definitely look this afternoon. If you have any other instructions for me to be of help in resolving this issue, I'm more than happy to execute; but understanding this all is a bit above my pay grade. :) Thank you so much for being on top of this.

**Comment by JELCRAWFORD** [comment] 2018-03-18 00:43
So, @jenm999  is running a with a 722 pump and has NO evidence of the skipping comment in the log with use of BW.  We are running with a 754 pump WITH the skipping happening with BW - @LongboatAline  - what pump are you using?  @alimhassam do you have any idea what the others elsewhere were using? @scottleibrand  -  can we assume if the pump version makes a difference than we are maybe looking at a decocare problem???  Or is there already an understanding of the fundamental nature of the problem?

**Comment by JELCRAWFORD** [comment] 2018-03-18 00:45
@alimhassam - I see your comments re; #954 - I think we can reliably produce the "skipping" - we'd need to update to dev to check though?  Currently running up to date master.

**Comment by tim2000s** [comment] 2018-03-18 01:49
@JELCRAWFORD - I’m on a 722 and tried this out today and didn’t have any issues with carbs disappearing.

**Comment by tim2000s** [comment] 2018-03-18 01:50
Firmware 2.4A 1.1

**Comment by alimhassam** [comment] 2018-03-18 02:06
@JELCRAWFORD the pull request hasn't been merged to dev yet. If you're relatively comfortable with checking out a pull request branch you can create a new branch from the pull request using something like
`git fetch origin pull/954/head:954test ` and  `git checkout 954test` (and do a bolus from the wizard ) to verify that it fixes the issue.

**Comment by alimhassam** [comment] 2018-03-18 02:09
@tim2000s 
 - which branch are you on? 
 - did you enter carbs via the bolus wizard? 
 - do you see a message in the pump-log saying the carbs are being `skipped` or can you confirm that you do you see the new carbs being accounted for in the pump loop?

Thanks!

**Comment by LongboatAline** [comment] 2018-03-18 15:56
@JELCRAWFORD I'm on a 754 as well, Firmware 2.6A 1.1 0B 0B

**Comment by tim2000s** [comment] 2018-03-18 19:57
I am on Dev and the carbs are accounted for in the pump-loop. I don’t use Bolus Wizard all the time, but when I tested it in response to this issue, had no problems.

**Comment by danamlewis** [comment] 2019-10-20 23:53
Per @tim2000s comment and latest 0.7.0-dev, I think this has been resolved. Please reopen if still an issue with current 0.7.0-dev.

**Closed by danamlewis** 2019-10-20 23:53 UTC
