### ISSUE TITLE
Carb ratio of 26 reported as 0.26 in profile.json

### ISSUE THREAD

**Issue by ryanchen26** [openaps/oref0#432] opened 2017-03-27 08:16 UTC
After changing a carb ratio setting in the pump (723) from 25 to 26 and running autotune manually autotune failed to run because of the error: carb ratio 0.26 out of range. The ratio change to 26 had been interpreted as 0.26 in profile.json.

**Comment by scottleibrand** [comment] 2017-07-03 17:48
This is caused by https://github.com/openaps/openaps/issues/111 - we'll need some folks to help figure out the underlying issue with decocare.

**Comment by scottleibrand** [comment] 2017-07-03 17:50
As a workaround, you could maybe set the carb ratio to 25 at midnight, and then let autotune adjust it upward from there.  To make sure you're actually bolusing off the correct carb ratio in the pump, you can then set  a 1am carb ratio to the correct value for the rest of the day.  @Mackwe

**Comment by Mackwe** [comment] 2017-07-03 18:49
Thank you @scottleibrand . I believe I don't have enough data yet for autotune to work and letting autosens free to change it about x2(!).. I think I would need to wait for https://github.com/openaps/openaps/issues/111 to get fixed (of fix it myself, but I lack time at the moment).

**Comment by YYGIRL** [comment] 2017-07-09 21:37
I have this issue @scottleibrand @Mackwe @ryanchen26. I troubleshooted with @kdisimone.  I am not running autotune, only autosens. It is causing me to get NaN errors and causes lots of other random errors including OpenAPS will set my temp basal to zero. OpenAPS will also not create a pumpprofile.json file. My son has been running very high in the afternoon and at night. I have a 723. This will affect a lot of little kids with an x23, and I know of at least another one (Leigh Fickling's daughter). My son's carb ratios are almost all above 25 (most are from 30-50) except for one - the one time of day he runs OK. Many thanks.

**Comment by YYGIRL** [comment] 2017-07-09 21:44
I am switching to my 722 for now, but any other workaround ideas would be great - for the community, and like I said especially for the little kids and for people who might not have another pump. Thanks again.

**Comment by scottleibrand** [comment] 2017-07-09 21:55
As a workaround, I could have oref0 multiply any < 1 carb ratios by 100 until someone fixes this properly in openaps/decocare. Our 723 supports 1.0 to 200, and the 522 supports 3.0 to 150, so we know that any reading < 1 is incorrect, and must really represent something in the 25-99 range. I don't know how CRs >= 100 show up, and whether any further adjustments would be needed there.

**Comment by YYGIRL** [comment] 2017-07-09 22:05
Yes! That would work. However, the r value is wrong as well? What is that? Is it used in calculations?

**Comment by scottleibrand** [comment] 2017-07-09 22:12
Does the `r` value match the `ratio` value?

We don't use `r` for anything in oref0, so I could probably just ignore that.  Since I'd be putting this workaround into oref0, the actual contents of carb_ratios.json would be unchanged: we would just apply the correction when creating the profile.json.

**Comment by scottleibrand** [comment] 2017-07-09 22:20
Ok, just pushed an as-yet-untested commit that implements the workaround.  If anyone currently running oref0 dev wants to test it, you can `cd ~/src/oref0` and `git checkout cr-decoding-workaround`.

**Comment by Kdisimone** [comment] 2017-07-09 22:22
I can setup a test rig for this later today

**Comment by YYGIRL** [comment] 2017-07-09 22:24
Here's a correct entry:
r: 230; ratio: 23.0
r: 80; ratio: 8.0
Incorrect entries (seems random, depending on time of day):
r: 32; ratio: 0.8
r: 34; ratio: 0.29
r: 244; ratio 0.5
r: 94; ratio 0.35
r: 144; ratio 0.4

So I think you could multiply the CR number coming in by 100 and get the ratio number; and you could multiply the CR number coming by 1000 and get the r number.

**Comment by Kdisimone** [comment] 2017-07-09 23:50
@scottleibrand do I also need to do an npm-global-install after the branch change?  thus far the fix isn't implementing the *100

**Comment by Kdisimone** [comment] 2017-07-09 23:50
```
glucose.json newer than pumphistory: Refreshed pumphistory
{"carbs":0,"mealCOB":0,"reason":"carb_ratio 0.57 out of bounds"}
```

**Comment by PieterGit** [comment] 2017-07-10 00:50
I'm -1 on implementing a workaround of changing carb ratio in oref0 instead of fixing the real problem in decocare or wherever. Please stick to https://en.wikipedia.org/wiki/Separation_of_concerns and make sure oref0 can trust the the carb ratio it gets. If it's not a oref0 bug, it should not be fixed in oref0.

**Comment by PieterGit** [comment] 2017-07-10 01:04
Just had a quick peek and search. Isn't this the logic where it goes wrong?
https://github.com/openaps/decocare/blob/6c87c83c8280850411a78b21005d217aaf06caa9/decocare/commands.py#L1000

**Comment by scottleibrand** [comment] 2017-07-10 02:45
@YYGIRL (or anyone else who's seeing this): could you paste in your full carb_ratios.json, as well as a list of what the carb ratio schedule actually is, so we can figure out how to adjust the https://github.com/openaps/decocare/blob/master/decocare/commands.py#L1000-L1002 logic to fix this properly?

**Comment by moomoobloo** [comment] 2017-07-10 03:45
I submitted https://github.com/openaps/decocare/pull/28, so probably the workaround isn't needed.

**Comment by Kdisimone** [comment] 2017-07-10 03:58
```
root@jubilinux:~/src/oref0# cat ~/myopenaps/settings/carb_ratios.json
{
  "units": "grams", 
  "first": 1, 
  "schedule": [
    {
      "q": 1, 
      "start": "00:00:00", 
      "r": 24, 
      "ratio": 0.28, 
      "offset": 0, 
      "i": 0, 
      "x": 0
    }, 
    {
      "q": 2, 
      "start": "16:00:00", 
      "r": 138, 
      "ratio": 0.65, 
      "offset": 960, 
      "i": 32, 
      "x": 1
    }, 
    {
      "q": 1, 
      "start": "17:30:00", 
      "r": 24, 
      "ratio": 0.28, 
      "offset": 1050, 
      "i": 35, 
      "x": 2
    }, 
    {
      "q": 2, 
      "start": "18:00:00", 
      "r": 58, 
      "ratio": 0.57, 
      "offset": 1080, 
      "i": 36, 
      "x": 3
    }
  ]
```

actual are (test pump)
midnight 28
4pm 65
5:30 28
6:00 57

**Comment by scottleibrand** [comment] 2017-07-10 04:08
@Kdisimone Did you check out and install openaps/decocare#28?  If so, which commands did you use?

**Comment by Kdisimone** [comment] 2017-07-10 04:09
I am testing it out.  I'm not so git saavy still so I manually edited file with 
`nano /home/.rootfs/usr/local/lib/python2.7/dist-packages/decocare/commands.py`
and then followed the changes in #28 

<img width="872" alt="screen shot 2017-07-09 at 9 04 02 pm" src="https://user-images.githubusercontent.com/12402160/28002528-df4bdd64-64ea-11e7-8a7f-b992b586e939.png">

**Comment by scottleibrand** [comment] 2017-07-10 04:22
I have no idea whether that file is the one actually being used by your system.  I would instead clone the decocare repo, get the fixed source code from @moomoobloo's branch using the command-line instructions (the part about how to check out a new branch and test the changes) in the merge section at the bottom of https://github.com/openaps/decocare/pull/28 .

Then, once you've verified you have the right source code, you can install that using these directions:
https://github.com/openaps/decocare#from-source

Hit me up on Slack or Gitter if you run into any trouble with that...

**Comment by Kdisimone** [comment] 2017-07-10 04:38
OK...I'll try that because it doesn't look like my attempt worked.  :)

**Comment by scottleibrand** [comment] 2017-07-17 00:38
Since https://github.com/openaps/decocare/pull/28 was merged to dev, It looks like the only thing remaining to do to resolve this is to release decocare dev to master, and update oref0 to install it.  Leaving this open for now until we get closer to that.  In the mean time, anyone affected by this issue can simply clone and install decocare dev.

**Comment by Kdisimone** [comment] 2017-07-24 01:57
Leaving the specific commands here for info:

**Closed** 2017-10-09 02:35 UTC
Labels: help wanted
