### ISSUE TITLE
oref0_online can stall a rpi3 rig if bluetooth is not used, and does not reconnect to the wlan

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#371] opened 2017-02-01 20:24 UTC
I have a setup without bluetooth tethering. I noticed my rig didn't reconnect to my wifi network and when I came back I could not log in over ssh. When I attached a keyboard and HDMI I found out:
- the rpi3 had a severe load and non responsiveness
- it didn't connect to the wifi network

I guess some of the bluetooth code / bluetooth tethering is causing problems when not used.

**Comment by scottleibrand** [comment] 2017-02-01 20:28
What did `top` say was causing the load?  Did `ps | grep openaps` show anything extra running?

I just noticed my Pi was busy with multiple `oref0-truncate-git` processes all running `du` - I need to update that cron job to only launch the script if it's not already running.

I don't think anything oref0-online is doing could cause severe load.  I'd be interested to see details if it can cause the rig not to reconnect to wifi, but it should fix most things that could cause that by restarting networking when you can't get online.

**Comment by PieterGit** [comment] 2017-02-01 20:37
I'll try to reproduce it later, but clearly oref0-online issues all kind of bluetooth commands which don't make any sense on a non-bluetooth setup

**Comment by scottleibrand** [comment] 2017-02-01 21:03
I'm not sure that's true.  First off, if the rig is online, and the rig has no bnep0 IP, then https://github.com/openaps/oref0/blob/dev/bin/oref0-online.sh#L8 is true and https://github.com/openaps/oref0/blob/dev/bin/oref0-online.sh#L10 is false, so it just exits.  If the rig is offline, and no arguments are passed to oref0-online, then https://github.com/openaps/oref0/blob/dev/bin/oref0-online.sh#L37 will be a for loop over an empty set, which I believe will mean it does nothing at that point.  If you can reproduce a problem there, we might need an additional if check on the existence of $1...

**Comment by scottleibrand** [comment] 2017-02-07 03:35
Have you seen this again since last week?

**Comment by jbwittmer** [comment] 2017-02-16 14:14
I'm experiencing something similar on a new setup of RP3 + TI stick without bluetooth rig that I just set up (with intention of using autotune part-time).

**Comment by scottleibrand** [comment] 2017-07-17 00:43
Closing in favor of https://github.com/openaps/oref0/issues/543

**Closed by scottleibrand** 2017-07-17 00:43 UTC
