### ISSUE TITLE
COB-aware autosens

### ISSUE THREAD

**Issue by sulkaharo** [openaps/oref0#430] opened 2017-03-26 16:06 UTC
The current autosens algorithm doesn't use COB data and just assumes rapid rises are always caused by carbs. Simultaneously at least on kids, it looks like hormonal activity alone can cause resistance / BG raises that all go over the current "assume it's carbs" threshold in autosens, so the algorithm can produce erroneous results on kids, sometimes to the point of increasing the sensitivity when the user is actually more resistant than the baseline. Making the algorithm COB aware should mitigate this a lot and would subsequently make it very beneficial for users to mark down all carb corrections to make the output more accurate.

A naive solution that could produce more accurate results would be to simply ignore the results if COB > 0; testing this approach would be needed. Some way of automating the testing would also be highly beneficial.

(Created a ticket for this in addition to the earlier chat discussion.)

**Comment by scottleibrand** [comment] 2017-03-26 17:00
This is a duplicate of #98, but since the problem description is better here, I'll leave this one open and close #98.

**Comment by scottleibrand** [comment] 2017-04-26 22:09
@MilosKozak just implemented this in https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/IobCobCalculator/IobCobCalculatorPlugin.java (thanks!) - any volunteers to port it back to js?

**Comment by scottleibrand** [comment] 2017-09-02 20:08
Implemented in #629.

**Closed** 2017-10-09 02:36 UTC
Labels: enhancement, help wanted
